import { ClanNode } from '../types/prestige';

export const CLAN_NODES: Record<string, ClanNode> = {
  // =========================================================================
  // TRONCO CENTRAL: ORIGEM OTSUTSUKI & O SÁBIO DOS SEIS CAMINHOS (8 NÓS)
  // =========================================================================
  primordial_chakra: {
    id: 'primordial_chakra',
    name: 'Chakra Primordial',
    branch: 'root',
    icon: 'primordial_chakra',
    cost: 1,
    desc: 'O despertar da centelha original do Sábio dos Seis Caminhos. +50% em todo o CPS global.',
    parent: null,
    cpsMultiplier: 1.5,
  },
  shinju_seed: {
    id: 'shinju_seed',
    name: 'Semente do Shinju',
    branch: 'root',
    icon: 'treepine',
    cost: 2,
    desc: 'O broto da Árvore Divina canaliza raízes astrais. +75% no CPS global.',
    parent: 'primordial_chakra',
    cpsMultiplier: 1.75,
  },
  ten_tails_resonance: {
    id: 'ten_tails_resonance',
    name: 'Ressonância do Dez-Caudas',
    branch: 'root',
    icon: 'flame',
    cost: 5,
    desc: 'A energia cósmica da Besta Primordial entra em simbiose. Dobra o CPS global (2x).',
    parent: 'shinju_seed',
    cpsMultiplier: 2.0,
  },
  hagoromo_blessing: {
    id: 'hagoromo_blessing',
    name: 'Bênção de Hagoromo',
    branch: 'root',
    icon: 'sun',
    cost: 12,
    desc: 'A sabedoria ancestral do Rikudō Sennin ilumina a circulação de chakra. +2.5x no CPS global.',
    parent: 'ten_tails_resonance',
    cpsMultiplier: 2.5,
  },
  hamura_celestial_will: {
    id: 'hamura_celestial_will',
    name: 'Vontade Celestial de Hamura',
    branch: 'root',
    icon: 'moon',
    cost: 25,
    desc: 'O irmão guardião da Lua compartilha a pureza celestial. +3x no CPS global.',
    parent: 'hagoromo_blessing',
    cpsMultiplier: 3.0,
  },
  six_paths_senjutsu: {
    id: 'six_paths_senjutsu',
    name: 'Senjutsu dos Seis Caminhos',
    branch: 'root',
    icon: 'sparkles',
    cost: 60,
    desc: 'A harmonia suprema de energia natural e vitalidade cósmica. +4x no CPS global.',
    parent: 'hamura_celestial_will',
    cpsMultiplier: 4.0,
  },
  divine_tree_core: {
    id: 'divine_tree_core',
    name: 'Núcleo da Árvore Divina',
    branch: 'root',
    icon: 'orbit',
    cost: 150,
    desc: 'O coração biológico que drena e renova as correntes telúricas do planeta. +5x no CPS global.',
    parent: 'six_paths_senjutsu',
    cpsMultiplier: 5.0,
  },
  infinite_genesis: {
    id: 'infinite_genesis',
    name: 'Gênese Shinobi Infinita',
    branch: 'root',
    icon: 'infinity',
    cost: 400,
    desc: 'A unificação definitiva de todas as ramificações de chakra do mundo. +10x no CPS global.',
    parent: 'divine_tree_core',
    cpsMultiplier: 10.0,
  },

  // =========================================================================
  // RAMO 1: SENJU & UZUMAKI (VITALIDADE, REGENERAÇÃO & MULTIPLICADORES CPS) (13 NÓS)
  // =========================================================================
  uzumaki_vitality: {
    id: 'uzumaki_vitality',
    name: 'Linhagem Uzumaki (Vitalidade Infinita)',
    branch: 'senju',
    icon: 'uzumaki_vitality',
    cost: 3,
    desc: 'Força vital e regeneração extraordinárias. Dobra todo o CPS global permanentemente.',
    parent: 'primordial_chakra',
    cpsMultiplier: 2.0,
  },
  adamantine_chains: {
    id: 'adamantine_chains',
    name: 'Correntes Adamantinas de Selamento',
    branch: 'senju',
    icon: 'shield',
    cost: 5,
    desc: 'Correntes de chakra dourado que aprisionam monstros de caudas. +50% no CPS global.',
    parent: 'uzumaki_vitality',
    cpsMultiplier: 1.5,
  },
  senju_wood_release: {
    id: 'senju_wood_release',
    name: 'Liberação de Madeira (Mokuton)',
    branch: 'senju',
    icon: 'senju_wood_release',
    cost: 8,
    desc: 'A fusão da terra com a água que molda florestas divinas. Triplica o CPS global (3x).',
    parent: 'adamantine_chains',
    cpsMultiplier: 3.0,
  },
  wood_dragon_jutsu: {
    id: 'wood_dragon_jutsu',
    name: 'Dragão Silvestre de Hashirama',
    branch: 'senju',
    icon: 'trees',
    cost: 15,
    desc: 'Uma serpente colossal de madeira que absorve o chakra dos oponentes. Dobra o CPS global (2x).',
    parent: 'senju_wood_release',
    cpsMultiplier: 2.0,
  },
  wood_golem_jutsu: {
    id: 'wood_golem_jutsu',
    name: 'Homem de Madeira Protetor',
    branch: 'senju',
    icon: 'shieldcheck',
    cost: 25,
    desc: 'O avatar titânico capaz de conter uma Bijū em combate corpo a corpo. +2.5x no CPS global.',
    parent: 'wood_dragon_jutsu',
    cpsMultiplier: 2.5,
  },
  shikkotsu_sage: {
    id: 'shikkotsu_sage',
    name: 'Modo Sábio da Floresta Shikkotsu',
    branch: 'senju',
    icon: 'leaf',
    cost: 45,
    desc: 'Comunhão medicinal com a lendária Lesma Katsuyu. Triplica o CPS global (3x).',
    parent: 'wood_golem_jutsu',
    cpsMultiplier: 3.0,
  },
  byakugou_seal: {
    id: 'byakugou_seal',
    name: 'Selo da Força de Uma Centena (Byakugō)',
    branch: 'senju',
    icon: 'circle_dot',
    cost: 80,
    desc: 'O losango na testa que armazena reservas astronômicas de chakra contínuo. +3.5x no CPS global.',
    parent: 'shikkotsu_sage',
    cpsMultiplier: 3.5,
  },
  mitotic_regeneration: {
    id: 'mitotic_regeneration',
    name: 'Criação do Renascimento (Sōzō Saisei)',
    branch: 'senju',
    icon: 'heartpulse',
    cost: 140,
    desc: 'Divisão celular instantânea que regenera tecidos vitais em milissegundos. +4x no CPS global.',
    parent: 'byakugou_seal',
    cpsMultiplier: 4.0,
  },
  shinsu_senju: {
    id: 'shinsu_senju',
    name: 'Verdadeiras Mil Mãos (Shinsūsenju)',
    branch: 'senju',
    icon: 'trees',
    cost: 250,
    desc: 'A invocação transcendental de madeira de Hashirama que altera a topografia da terra. +5x no CPS global.',
    parent: 'mitotic_regeneration',
    cpsMultiplier: 5.0,
  },
  uzumaki_fuinjutsu_mastery: {
    id: 'uzumaki_fuinjutsu_mastery',
    name: 'Maestria Fūinjutsu de Uzushio',
    branch: 'senju',
    icon: 'scroll',
    cost: 450,
    desc: 'Selamentos proibidos da aldeia dos redemoinhos que retêm chakra perpétuo. +6x no CPS global.',
    parent: 'shinsu_senju',
    cpsMultiplier: 6.0,
  },
  gate_of_the_great_god: {
    id: 'gate_of_the_great_god',
    name: 'Portais Torii do Grande Deus',
    branch: 'senju',
    icon: 'crown',
    cost: 800,
    desc: 'Selos celestiais em forma de arcos vermelhos que imobilizam divindades. +7.5x no CPS global.',
    parent: 'uzumaki_fuinjutsu_mastery',
    cpsMultiplier: 7.5,
  },
  reanimation_secret: {
    id: 'reanimation_secret',
    name: 'Segredos Proibidos do Segundo Hokage',
    branch: 'senju',
    icon: 'ghost',
    cost: 1500,
    desc: 'A maestria transcendental de Tobirama Senju dobrando a eficiência energética. +10x no CPS global.',
    parent: 'gate_of_the_great_god',
    cpsMultiplier: 10.0,
  },
  will_of_fire_primordial: {
    id: 'will_of_fire_primordial',
    name: 'Vontade do Fogo Primordial',
    branch: 'senju',
    icon: 'flame',
    cost: 3500,
    desc: 'A convicção imortal que queima no espírito de cada shinobi da Folha. Multiplica todo o CPS por 20x.',
    parent: 'reanimation_secret',
    cpsMultiplier: 20.0,
  },

  // =========================================================================
  // RAMO 2: UCHIHA (PODER OCULAR, FOGO NEGRO & ACERTOS CRÍTICOS) (14 NÓS)
  // =========================================================================
  sharingan_awakening: {
    id: 'sharingan_awakening',
    name: 'Despertar do Sharingan (1-Tomoe)',
    branch: 'uchiha',
    icon: 'sharingan_awakening',
    cost: 3,
    desc: 'O olho copiado do Clã Uchiha. Aumenta a chance de acerto crítico de clique em +10%.',
    parent: 'primordial_chakra',
    critChanceBonus: 10,
  },
  sharingan_two_tomoe: {
    id: 'sharingan_two_tomoe',
    name: 'Sharingan de Dois Tomoes',
    branch: 'uchiha',
    icon: 'eye',
    cost: 6,
    desc: 'Percepção acelerada dos movimentos inimigos. +5% Chance Crítica e +50% no Poder de Clique.',
    parent: 'sharingan_awakening',
    critChanceBonus: 5,
    clickMultiplier: 1.5,
  },
  sharingan_three_tomoe: {
    id: 'sharingan_three_tomoe',
    name: 'Sharingan Triplo Completo',
    branch: 'uchiha',
    icon: 'eye',
    cost: 10,
    desc: 'Previsão de jutsus e hipnose ocular em combate. +8% Chance Crítica e Dobra o Poder de Clique (2x).',
    parent: 'sharingan_two_tomoe',
    critChanceBonus: 8,
    clickMultiplier: 2.0,
  },
  mangekyo_sharingan_lineage: {
    id: 'mangekyo_sharingan_lineage',
    name: 'Mangekyō Sharingan Eterno',
    branch: 'uchiha',
    icon: 'mangekyo_sharingan_lineage',
    cost: 18,
    desc: 'O olho celestial que reflete o coração. O clique manual passa a gerar +3% do seu CPS global.',
    parent: 'sharingan_three_tomoe',
    clickMultiplier: 2.5,
  },
  tsukuyomi_realm: {
    id: 'tsukuyomi_realm',
    name: 'Pesadelo de Tsukuyomi',
    branch: 'uchiha',
    icon: 'moon',
    cost: 30,
    desc: 'Controle absoluto do tempo, espaço e massa no plano ilusório. +3x no Poder de Clique.',
    parent: 'mangekyo_sharingan_lineage',
    clickMultiplier: 3.0,
  },
  amaterasu_eternal_flame: {
    id: 'amaterasu_eternal_flame',
    name: 'Chamas Negras Inextinguíveis (Amaterasu)',
    branch: 'uchiha',
    icon: 'flame',
    cost: 50,
    desc: 'Fogo negro que queima por sete dias e sete noites sem cessar. +12% Chance Crítica.',
    parent: 'tsukuyomi_realm',
    critChanceBonus: 12,
  },
  kagutsuchi_flame_control: {
    id: 'kagutsuchi_flame_control',
    name: 'Controle de Chamas (Enton Kagutsuchi)',
    branch: 'uchiha',
    icon: 'flame',
    cost: 90,
    desc: 'Moldar as chamas negras em lanças, espadas e flechas cortantes. +4x no Poder de Clique.',
    parent: 'amaterasu_eternal_flame',
    clickMultiplier: 4.0,
  },
  susanoo_ribcage: {
    id: 'susanoo_ribcage',
    name: 'Costelas Protetoras do Susano\'o',
    branch: 'uchiha',
    icon: 'shield',
    cost: 150,
    desc: 'A primeira manifestação óssea do guerreiro etéreo. Dobra o Poder de Clique e +10% Crítico.',
    parent: 'kagutsuchi_flame_control',
    clickMultiplier: 2.0,
    critChanceBonus: 10,
  },
  susanoo_skeletal: {
    id: 'susanoo_skeletal',
    name: 'Esqueleto do Guerreiro Espiritual',
    branch: 'uchiha',
    icon: 'skull',
    cost: 250,
    desc: 'Músculos e tecido de chakra envolvendo o esqueleto guerreiro. +5x no Poder de Clique.',
    parent: 'susanoo_ribcage',
    clickMultiplier: 5.0,
  },
  susanoo_armored: {
    id: 'susanoo_armored',
    name: 'Armadura Tengu de Batalha',
    branch: 'uchiha',
    icon: 'swords',
    cost: 450,
    desc: 'A couraça lendária das divindades xintoístas com lâminas gêmeas. +7x no Poder de Clique.',
    parent: 'susanoo_skeletal',
    clickMultiplier: 7.0,
  },
  perfect_susanoo_lineage: {
    id: 'perfect_susanoo_lineage',
    name: 'Susano\'o Perfeito Divino',
    branch: 'uchiha',
    icon: 'perfect_susanoo_lineage',
    cost: 800,
    desc: 'O colosso de armadura completa capaz de cortar montanhas ao meio. Multiplica o Clique por 10x.',
    parent: 'susanoo_armored',
    clickMultiplier: 10.0,
  },
  kamui_space_phase: {
    id: 'kamui_space_phase',
    name: 'Intangibilidade e Vácuo Kamui',
    branch: 'uchiha',
    icon: 'orbit',
    cost: 1400,
    desc: 'Deslocamento interdimensional que evade qualquer dano e amplifica golpes. +15% Chance Crítica.',
    parent: 'perfect_susanoo_lineage',
    critChanceBonus: 15,
  },
  kotoamatsukami_will: {
    id: 'kotoamatsukami_will',
    name: 'Miragem Soberana (Kotoamatsukami)',
    branch: 'uchiha',
    icon: 'eye',
    cost: 2500,
    desc: 'O genjutsu definitivo de Shisui Uchiha que reescreve a vontade cósmica. +15x no Poder de Clique.',
    parent: 'kamui_space_phase',
    clickMultiplier: 15.0,
  },
  indra_divine_arrow: {
    id: 'indra_divine_arrow',
    name: 'Flecha Celestial de Indra',
    branch: 'uchiha',
    icon: 'zap',
    cost: 5000,
    desc: 'O golpe mais destrutivo de Sasuke Uchiha canalizando todas as Bijūs. +25x Poder de Clique e +20% Crítico.',
    parent: 'kotoamatsukami_will',
    clickMultiplier: 25.0,
    critChanceBonus: 20,
  },

  // =========================================================================
  // RAMO 3: HYŪGA & TENSEIGAN (VISÃO 360°, TENKETSU & RECOMPENSAS) (12 NÓS)
  // =========================================================================
  byakugan_vision: {
    id: 'byakugan_vision',
    name: 'Visão dos 360 Graus (Byakugan)',
    branch: 'hyuga',
    icon: 'byakugan_vision',
    cost: 3,
    desc: 'Leitura dos pontos de chakra (Tenketsu). +50% nas recompensas de ouro e missões.',
    parent: 'primordial_chakra',
    rewardMultiplier: 1.5,
  },
  gentle_fist_stance: {
    id: 'gentle_fist_stance',
    name: 'Postura do Punho Suave (Jūken)',
    branch: 'hyuga',
    icon: 'hand',
    cost: 6,
    desc: 'Golpes que penetram o fluxo de chakra do oponente sem causar ferimentos externos. +25% no CPS global.',
    parent: 'byakugan_vision',
    cpsMultiplier: 1.25,
  },
  eight_trigrams_palms: {
    id: 'eight_trigrams_palms',
    name: 'As Oito Trigramas de Konoha',
    branch: 'hyuga',
    icon: 'compass',
    cost: 12,
    desc: 'O círculo sagrado de adivinhação taoísta que prevê o fluxo de chakra. +50% no CPS global.',
    parent: 'gentle_fist_stance',
    cpsMultiplier: 1.5,
  },
  kaiten_rotation: {
    id: 'kaiten_rotation',
    name: 'Rotação Divina Celestial (Kaiten)',
    branch: 'hyuga',
    icon: 'shieldcheck',
    cost: 20,
    desc: 'A defesa absoluta dos Hyūga que libera chakra pelos 361 tenketsu simultaneamente. +75% no CPS.',
    parent: 'eight_trigrams_palms',
    cpsMultiplier: 1.75,
  },
  sixty_four_palms: {
    id: 'sixty_four_palms',
    name: 'Oito Trigramas: Sessenta e Quatro Palmas',
    branch: 'hyuga',
    icon: 'target',
    cost: 35,
    desc: 'Bloqueio cirúrgico dos tenketsu vitais. Dobra todas as recompensas de missões e chefes (2x).',
    parent: 'kaiten_rotation',
    rewardMultiplier: 2.0,
  },
  one_hundred_twenty_eight_palms: {
    id: 'one_hundred_twenty_eight_palms',
    name: 'Cento e Vinte e Oito Palmas',
    branch: 'hyuga',
    icon: 'zap',
    cost: 65,
    desc: 'O dobro de velocidade na execução dos trigramas. Dobra o CPS global (2x).',
    parent: 'sixty_four_palms',
    cpsMultiplier: 2.0,
  },
  twin_lion_fists: {
    id: 'twin_lion_fists',
    name: 'Punhos dos Leões Gêmeos (Jūho Sōshiken)',
    branch: 'hyuga',
    icon: 'flame',
    cost: 120,
    desc: 'Chakra moldado em formato de leões ferozes que drenam a energia ao tocar. +2.5x no Poder de Clique.',
    parent: 'one_hundred_twenty_eight_palms',
    clickMultiplier: 2.5,
  },
  air_palm_cannon: {
    id: 'air_palm_cannon',
    name: 'Canhão de Vácuo Oito Trigramas',
    branch: 'hyuga',
    icon: 'wind',
    cost: 220,
    desc: 'Ondas de choque compressas disparadas a longa distância. +2.5x no CPS global.',
    parent: 'twin_lion_fists',
    cpsMultiplier: 2.5,
  },
  byakugan_clairvoyance: {
    id: 'byakugan_clairvoyance',
    name: 'Clarividência Óptica da Névoa',
    branch: 'hyuga',
    icon: 'eye',
    cost: 400,
    desc: 'Visão através de qualquer barreira sólida ou camuflagem sensorial. Triplica as Recompensas (3x).',
    parent: 'air_palm_cannon',
    rewardMultiplier: 3.0,
  },
  silver_wheel_reincarnation: {
    id: 'silver_wheel_reincarnation',
    name: 'Explosão da Roda Prateada (Ginrin)',
    branch: 'hyuga',
    icon: 'sparkles',
    cost: 800,
    desc: 'Um tufão prateado de chakra que devasta exércitos inteiros. +4x no CPS global.',
    parent: 'byakugan_clairvoyance',
    cpsMultiplier: 4.0,
  },
  golden_wheel_reincarnation: {
    id: 'golden_wheel_reincarnation',
    name: 'Espada da Roda Dourada (Kinrin)',
    branch: 'hyuga',
    icon: 'sword',
    cost: 1800,
    desc: 'A lâmina estelar dourada capaz de partir a Lua de ponta a ponta. +6x no CPS e +5x no Clique.',
    parent: 'silver_wheel_reincarnation',
    cpsMultiplier: 6.0,
    clickMultiplier: 5.0,
  },
  tenseigan_rebirth: {
    id: 'tenseigan_rebirth',
    name: 'Renascimento Cósmico do Tenseigan',
    branch: 'hyuga',
    icon: 'sun',
    cost: 4500,
    desc: 'A evolução divina máxima dos olhos dos Hyūga e Otsutsuki. +12x no CPS e +5x nas Recompensas.',
    parent: 'golden_wheel_reincarnation',
    cpsMultiplier: 12.0,
    rewardMultiplier: 5.0,
  },

  // =========================================================================
  // RAMO 4: OTSUTSUKI CELESTIAL (PODER DIVINO & DIMENSÕES) (13 NÓS)
  // =========================================================================
  chakra_fruit: {
    id: 'chakra_fruit',
    name: 'Fruto Proibido do Clã Divino',
    branch: 'otsutsuki',
    icon: 'chakra_fruit',
    cost: 30,
    desc: 'Consumo do fruto primordial de chakra da Shinju. Multiplica todo o CPS global em 5x.',
    parent: 'primordial_chakra',
    cpsMultiplier: 5.0,
  },
  rinne_sharingan_eye: {
    id: 'rinne_sharingan_eye',
    name: 'Olho Supremo da Lua Vermelha (Rinne Sharingan)',
    branch: 'otsutsuki',
    icon: 'eye',
    cost: 60,
    desc: 'O terceiro olho na testa de Kaguya que domina todos os tipos de chakra. +3x CPS e +3x Clique.',
    parent: 'chakra_fruit',
    cpsMultiplier: 3.0,
    clickMultiplier: 3.0,
  },
  truth_seeking_mastery: {
    id: 'truth_seeking_mastery',
    name: 'Esferas da Busca da Verdade (Gudōdama)',
    branch: 'otsutsuki',
    icon: 'orbit',
    cost: 110,
    desc: 'Orbes negras contendo todas as cinco naturezas e o Yin-Yang. +4x no CPS global.',
    parent: 'rinne_sharingan_eye',
    cpsMultiplier: 4.0,
  },
  deva_path_gravity: {
    id: 'deva_path_gravity',
    name: 'Caminho Deva (Domínio Gravitacional)',
    branch: 'otsutsuki',
    icon: 'compass',
    cost: 200,
    desc: 'Atração (Banshō Ten\'in) e repulsão (Shinra Tensei) manipulando a gravidade. +4.5x no CPS.',
    parent: 'truth_seeking_mastery',
    cpsMultiplier: 4.5,
  },
  preta_path_absorption: {
    id: 'preta_path_absorption',
    name: 'Caminho Preta (Absorção de Jutsus)',
    branch: 'otsutsuki',
    icon: 'shield',
    cost: 350,
    desc: 'Barreira que drena instantaneamente qualquer ninjutsu direcionado. +5x no CPS global.',
    parent: 'deva_path_gravity',
    cpsMultiplier: 5.0,
  },
  asura_path_arsenal: {
    id: 'asura_path_arsenal',
    name: 'Caminho Asura (Mecanização Bélica)',
    branch: 'otsutsuki',
    icon: 'swords',
    cost: 600,
    desc: 'Canhões de energia e projéteis mecânicos ocultos sob a pele. +6x no Poder de Clique.',
    parent: 'preta_path_absorption',
    clickMultiplier: 6.0,
  },
  chibaku_tensei_celestial: {
    id: 'chibaku_tensei_celestial',
    name: 'Devastação Planetária (Chibaku Tensei)',
    branch: 'otsutsuki',
    icon: 'moon',
    cost: 1100,
    desc: 'Criação de um satélite lunar para aprisionar qualquer ameaça cósmica. +7x no CPS global.',
    parent: 'asura_path_arsenal',
    cpsMultiplier: 7.0,
  },
  amenotejikara_shift: {
    id: 'amenotejikara_shift',
    name: 'Transposição Espacial (Amenotejikara)',
    branch: 'otsutsuki',
    icon: 'zap',
    cost: 2000,
    desc: 'Troca instantânea de lugar entre qualquer objeto ou oponente no campo de visão. +8x no Clique.',
    parent: 'chibaku_tensei_celestial',
    clickMultiplier: 8.0,
  },
  yomotsu_hirasaka: {
    id: 'yomotsu_hirasaka',
    name: 'Fenda Dimensional de Yomotsu Hirasaka',
    branch: 'otsutsuki',
    icon: 'door_open',
    cost: 3500,
    desc: 'O ninjutsu de espaço-tempo original que conecta as seis dimensões paralelas. +9x no CPS global.',
    parent: 'amenotejikara_shift',
    cpsMultiplier: 9.0,
  },
  karma_seal_stage_one: {
    id: 'karma_seal_stage_one',
    name: 'Selo Karma (Despertar do Receptáculo)',
    branch: 'otsutsuki',
    icon: 'hexagon',
    cost: 6000,
    desc: 'O arquivo biológico compactado contendo milênios de experiência de combate. +10x no CPS global.',
    parent: 'yomotsu_hirasaka',
    cpsMultiplier: 10.0,
  },
  karma_seal_stage_two: {
    id: 'karma_seal_stage_two',
    name: 'Ressonância do Karma Celestial',
    branch: 'otsutsuki',
    icon: 'sparkles',
    cost: 12000,
    desc: 'Manifestação dos chifres celestes e linhas brilhantes pelo corpo. +15x CPS e +10x Clique.',
    parent: 'karma_seal_stage_one',
    cpsMultiplier: 15.0,
    clickMultiplier: 10.0,
  },
  divine_god_tree_bloom: {
    id: 'divine_god_tree_bloom',
    name: 'Florescimento da Árvore Divina Cósmica',
    branch: 'otsutsuki',
    icon: 'trees',
    cost: 25000,
    desc: 'A flor da Shinju desabrochando com o poder de absorver oceanos de chakra planetário. +25x no CPS.',
    parent: 'karma_seal_stage_two',
    cpsMultiplier: 25.0,
  },
  otsutsuki_god_ascension: {
    id: 'otsutsuki_god_ascension',
    name: 'Ascensão ao Deus Supremo Otsutsuki (Shibai)',
    branch: 'otsutsuki',
    icon: 'crown',
    cost: 60000,
    desc: 'A transcendência para o plano das divindades que moldam a realidade sem selos de mão. +50x CPS e +20x Clique.',
    parent: 'divine_god_tree_bloom',
    cpsMultiplier: 50.0,
    clickMultiplier: 20.0,
  },
};
