import { D } from '../engine/BigNumber';
import {
  EquipmentItem,
  FarmMaterialItem,
  ItemRarity,
} from '../types/inventory';

export interface BossLootDefinition {
  bossId: number;
  bossName: string;
  equipment: EquipmentItem;
  material: Omit<FarmMaterialItem, 'stackCount'>;
}

/**
 * Curva Matemática de Chance de Drop:
 * P_drop(n) = max(0.005, 0.25 * 0.96^(n - 1))
 * - Chefes Iniciais (1-15): 25% -> 15%
 * - Chefes Intermediários (16-45): 15% -> 5%
 * - Chefes Avançados (46-75): 5% -> 2%
 * - Chefes de Endgame (76-100+): 2% -> 0.5%
 */
export function calculateBossDropProbability(n: number): number {
  const prob = 0.25 * Math.pow(0.96, Math.max(0, n - 1));
  return Math.max(0.005, prob);
}

/**
 * Tabela Oficial de Equipamentos Canônicos e Mercadorias/Materiais por Chefe
 */
export const BOSS_LOOT_CATALOG: Record<number, BossLootDefinition> = {
  1: {
    bossId: 1,
    bossName: 'Mizuki',
    equipment: {
      id: 'eq_mizuki_vest',
      name: 'Colete da Academia Rasgado',
      rarity: 'COMMON',
      type: 'ARMOR',
      description: 'Colete shinobi básico rasgado durante o confronto no bosque de Konoha.',
      iconName: 'Shield',
      bonusCpsMult: D(1.03), // +3% CPS
      bonusClickMult: D(1.0),
      originBossId: 1,
      originBossName: 'Mizuki',
    },
    material: {
      id: 'mat_giant_shuriken',
      name: 'Shuriken Gigante Enferrujada',
      rarity: 'COMMON',
      type: 'MATERIAL',
      description: 'Arma de arremesso pesada marcada por lâminas corroídas pelo tempo.',
      iconName: 'Disc',
      baseGoldValue: D(50),
      originBossId: 1,
      originBossName: 'Mizuki',
    },
  },
  2: {
    bossId: 2,
    bossName: 'Ebisu & Força Policial de Konoha',
    equipment: {
      id: 'eq_ebisu_bandana',
      name: 'Bandana Ninja de Treinamento Especial',
      rarity: 'COMMON',
      type: 'ARMOR',
      description: 'Protetor de testa reforçado utilizado pelo instrutor de elite de Konoha.',
      iconName: 'Shield',
      bonusCpsMult: D(1.04),
      bonusClickMult: D(1.05),
      originBossId: 2,
      originBossName: 'Ebisu & Força Policial',
    },
    material: {
      id: 'mat_tactical_chalk',
      name: 'Giz Tático de Treinamento',
      rarity: 'COMMON',
      type: 'MATERIAL',
      description: 'Composto mineral usado para traçar selos provisórios no solo da academia.',
      iconName: 'Sparkles',
      baseGoldValue: D(100),
      originBossId: 2,
      originBossName: 'Ebisu',
    },
  },
  3: {
    bossId: 3,
    bossName: 'Kankurō',
    equipment: {
      id: 'eq_kankuro_hood',
      name: 'Capuz do Titereiro Negro',
      rarity: 'COMMON',
      type: 'ARMOR',
      description: 'Capuz característico de marionetista de Sunagakure, afinado para fluxo de vento.',
      iconName: 'Shield',
      bonusCpsMult: D(1.06),
      bonusClickMult: D(1.0),
      elementalAffinityReq: 'WIND',
      elementalBonusCpsMult: D(1.05),
      originBossId: 3,
      originBossName: 'Kankurō',
    },
    material: {
      id: 'mat_chakra_threads',
      name: 'Fio de Chakra Reforçado',
      rarity: 'COMMON',
      type: 'MATERIAL',
      description: 'Filamento maleável para controle preciso de engrenagens de marionetes.',
      iconName: 'Feather',
      baseGoldValue: D(160),
      originBossId: 3,
      originBossName: 'Kankurō',
    },
  },
  4: {
    bossId: 4,
    bossName: 'Genno',
    equipment: {
      id: 'eq_genno_pouch',
      name: 'Algibeira de Selos Explosivos',
      rarity: 'UNCOMMON',
      type: 'ARMOR',
      description: 'Bolsa tática de armadilheiro mestre com compartimentos para detonações rápidas.',
      iconName: 'Shield',
      bonusCpsMult: D(1.0),
      bonusClickMult: D(1.10),
      bonusCritChance: 0.03,
      originBossId: 4,
      originBossName: 'Genno',
    },
    material: {
      id: 'mat_trap_detonator',
      name: 'Detonador Arcaico de Armadilha',
      rarity: 'UNCOMMON',
      type: 'MATERIAL',
      description: 'Mecanismo de gatilho oculto desenvolvido pelo veterano artilheiro Genno.',
      iconName: 'Flame',
      baseGoldValue: D(250),
      originBossId: 4,
      originBossName: 'Genno',
    },
  },
  5: {
    bossId: 5,
    bossName: 'Amachi',
    equipment: {
      id: 'eq_kubikiribocho',
      name: 'Kubikiribōchō - Espada Decapitadora',
      rarity: 'RARE',
      type: 'WEAPON',
      weaponCategory: 'SWORD',
      description: 'A lendária lâmina da Névoa Sangrenta que se regenera através do sangue dos inimigos cortados.',
      iconName: 'Swords',
      bonusCpsMult: D(1.0),
      bonusClickMult: D(1.25), // +25% Clique
      bonusCritMult: D(1.20),
      bonusCritChance: 0.05,
      elementalAffinityReq: 'WATER',
      elementalBonusClickMult: D(1.15),
      originBossId: 5,
      originBossName: 'Amachi / Zabuza',
    },
    material: {
      id: 'mat_mist_iron',
      name: 'Fragmento de Ferro da Névoa Sangrenta',
      rarity: 'RARE',
      type: 'MATERIAL',
      description: 'Liga ferrosa maleável de Kirigakure com propriedade regenerativa única.',
      iconName: 'Boxes',
      baseGoldValue: D(400),
      originBossId: 5,
      originBossName: 'Amachi',
    },
  },
  6: {
    bossId: 6,
    bossName: 'Ishidate',
    equipment: {
      id: 'eq_petrify_gauntlet',
      name: 'Manopla Petrificadora de Pedra',
      rarity: 'UNCOMMON',
      type: 'ARMOR',
      description: 'Manopla canalizadora que infunde chakra Doton denso nos impactos.',
      iconName: 'Shield',
      bonusCpsMult: D(1.12),
      bonusClickMult: D(1.05),
      elementalAffinityReq: 'EARTH',
      elementalBonusCpsMult: D(1.08),
      originBossId: 6,
      originBossName: 'Ishidate',
    },
    material: {
      id: 'mat_petrified_shard',
      name: 'Fragmento de Rocha Petrificada',
      rarity: 'UNCOMMON',
      type: 'MATERIAL',
      description: 'Resíduo de rocha gerado pela técnica proibida de petrificação celular.',
      iconName: 'Mountain',
      baseGoldValue: D(550),
      originBossId: 6,
      originBossName: 'Ishidate',
    },
  },
  7: {
    bossId: 7,
    bossName: 'Dotō Kazahana',
    equipment: {
      id: 'eq_snow_chakra_armor',
      name: 'Armadura de Chakra do País da Neve',
      rarity: 'UNCOMMON',
      type: 'ARMOR',
      description: 'Armadura mecânica prototípica capaz de absorver impactos de ninjutsu elementais.',
      iconName: 'Shield',
      bonusCpsMult: D(1.15),
      bonusClickMult: D(1.10),
      originBossId: 7,
      originBossName: 'Dotō Kazahana',
    },
    material: {
      id: 'mat_ice_crystal',
      name: 'Cristal Hexagonal de Gelo Puro',
      rarity: 'UNCOMMON',
      type: 'MATERIAL',
      description: 'Cristal condensado sob temperaturas negativas extremas do País da Neve.',
      iconName: 'Sparkles',
      baseGoldValue: D(750),
      originBossId: 7,
      originBossName: 'Dotō Kazahana',
    },
  },
  8: {
    bossId: 8,
    bossName: 'Shiranami',
    equipment: {
      id: 'eq_tsuchigumo_robe',
      name: 'Manto de Selamento Tsuchigumo',
      rarity: 'UNCOMMON',
      type: 'ARMOR',
      description: 'Veste cerimonial bordada com os kanjis da técnica de liberação furiosa.',
      iconName: 'Shield',
      bonusCpsMult: D(1.18),
      bonusClickMult: D(1.05),
      originBossId: 8,
      originBossName: 'Shiranami',
    },
    material: {
      id: 'mat_forbidden_kanji_scroll',
      name: 'Pergaminho de Kanjis Proibidos',
      rarity: 'UNCOMMON',
      type: 'MATERIAL',
      description: 'Escritura tática contendo caracteres antigos de confinamento corporal.',
      iconName: 'Scroll',
      baseGoldValue: D(1050),
      originBossId: 8,
      originBossName: 'Shiranami',
    },
  },
  9: {
    bossId: 9,
    bossName: 'Jirōbō',
    equipment: {
      id: 'eq_jirobo_bracers',
      name: 'Braçadeiras do Portão da Terra',
      rarity: 'UNCOMMON',
      type: 'ARMOR',
      description: 'Braçadeiras rochosas pesadas que canalizam o solo sob os pés do usuário.',
      iconName: 'Shield',
      bonusCpsMult: D(1.20),
      bonusClickMult: D(1.08),
      elementalAffinityReq: 'EARTH',
      elementalBonusCpsMult: D(1.10),
      originBossId: 9,
      originBossName: 'Jirōbō',
    },
    material: {
      id: 'mat_crushed_earth_stone',
      name: 'Rocha de Chakra Esmagada',
      rarity: 'UNCOMMON',
      type: 'MATERIAL',
      description: 'Bloco de rocha compactada arrancado do terreno durante a prisão de terra.',
      iconName: 'Mountain',
      baseGoldValue: D(1450),
      originBossId: 9,
      originBossName: 'Jirōbō',
    },
  },
  10: {
    bossId: 10,
    bossName: 'Sakon e Ukon',
    equipment: {
      id: 'eq_curse_mark_mantle',
      name: 'Manto dos Irmãos Siameses',
      rarity: 'RARE',
      type: 'ARMOR',
      description: 'Manto infundido com o chakra mutagênico do Selo da Maldição Nível 2.',
      iconName: 'Shield',
      bonusCpsMult: D(1.22),
      bonusClickMult: D(1.15),
      bonusCritChance: 0.04,
      originBossId: 10,
      originBossName: 'Sakon e Ukon',
    },
    material: {
      id: 'mat_parasite_cells',
      name: 'Células Parasitárias da Marca da Maldição',
      rarity: 'RARE',
      type: 'MATERIAL',
      description: 'Fragmento orgânico altamente reativo capaz de fusão celular profunda.',
      iconName: 'Feather',
      baseGoldValue: D(2100),
      originBossId: 10,
      originBossName: 'Sakon e Ukon',
    },
  },
  11: {
    bossId: 11,
    bossName: 'Tayuya',
    equipment: {
      id: 'eq_demon_flute',
      name: 'Flauta Demoníaca dos Doki',
      rarity: 'RARE',
      type: 'WEAPON',
      weaponCategory: 'SWORD',
      description: 'Instrumento forjado para entoar melodias ilusórias que paralisam o sistema nervoso.',
      iconName: 'Swords',
      bonusCpsMult: D(1.10),
      bonusClickMult: D(1.30),
      bonusCritChance: 0.06,
      elementalAffinityReq: 'WIND',
      elementalBonusClickMult: D(1.15),
      originBossId: 11,
      originBossName: 'Tayuya',
    },
    material: {
      id: 'mat_doki_summon_seal',
      name: 'Selo de Invocação Espectral dos Doki',
      rarity: 'RARE',
      type: 'MATERIAL',
      description: 'Pergaminho de sangue contendo as coordenadas das entidades devoradoras de chakra.',
      iconName: 'Scroll',
      baseGoldValue: D(2900),
      originBossId: 11,
      originBossName: 'Tayuya',
    },
  },
  12: {
    bossId: 12,
    bossName: 'Baki da Areia',
    equipment: {
      id: 'eq_blade_of_wind',
      name: 'Lâmina Invisível da Lufada de Vento',
      rarity: 'RARE',
      type: 'WEAPON',
      weaponCategory: 'BLADE',
      description: 'Lâmina incorpórea formada puramente por correntes de ar altamente condensadas.',
      iconName: 'Swords',
      bonusCpsMult: D(1.0),
      bonusClickMult: D(1.35),
      bonusCritChance: 0.06,
      elementalAffinityReq: 'WIND',
      elementalBonusClickMult: D(1.20),
      originBossId: 12,
      originBossName: 'Baki da Areia',
    },
    material: {
      id: 'mat_sharpened_wind_sand',
      name: 'Areia Afiada por Ventania Cortante',
      rarity: 'RARE',
      type: 'MATERIAL',
      description: 'Minério arenoso polido por furacões contínuos no deserto de Sunagakure.',
      iconName: 'Wind',
      baseGoldValue: D(3900),
      originBossId: 12,
      originBossName: 'Baki da Areia',
    },
  },
  13: {
    bossId: 13,
    bossName: 'Haido',
    equipment: {
      id: 'eq_gelel_armor',
      name: 'Armadura da Pedra Filosofal de Gelel',
      rarity: 'RARE',
      type: 'ARMOR',
      description: 'Couraça cerimonial embutida com veios de energia fóssil primordial de Gelel.',
      iconName: 'Shield',
      bonusCpsMult: D(1.32),
      bonusClickMult: D(1.20),
      originBossId: 13,
      originBossName: 'Haido',
    },
    material: {
      id: 'mat_gelel_ore',
      name: 'Fragmento Puro de Pedra de Gelel',
      rarity: 'RARE',
      type: 'MATERIAL',
      description: 'Minério lendário que emana radiação benéfica de regeneração vital contínua.',
      iconName: 'Sparkles',
      baseGoldValue: D(5200),
      originBossId: 13,
      originBossName: 'Haido',
    },
  },
  14: {
    bossId: 14,
    bossName: 'Toroi da Nuvem',
    equipment: {
      id: 'eq_magnet_shuriken',
      name: 'Shuriken Magnética de Colisão',
      rarity: 'RARE',
      type: 'WEAPON',
      weaponCategory: 'BLADE',
      description: 'Lâmina giratória polarizada com Liberação de Magnetismo de Kumogakure.',
      iconName: 'Swords',
      bonusCpsMult: D(1.0),
      bonusClickMult: D(1.40),
      bonusCritChance: 0.07,
      elementalAffinityReq: 'LIGHTNING',
      elementalBonusClickMult: D(1.20),
      originBossId: 14,
      originBossName: 'Toroi da Nuvem',
    },
    material: {
      id: 'mat_conductive_magnetite',
      name: 'Minério de Magnetita Conduzida',
      rarity: 'RARE',
      type: 'MATERIAL',
      description: 'Metal magnético com imantação perpétua imune a despolarizações normais.',
      iconName: 'Boxes',
      baseGoldValue: D(7200),
      originBossId: 14,
      originBossName: 'Toroi',
    },
  },
  15: {
    bossId: 15,
    bossName: 'Gari da Pedra',
    equipment: {
      id: 'eq_explosion_gauntlets',
      name: 'Manoplas do Punho de Explosão',
      rarity: 'RARE',
      type: 'ARMOR',
      description: 'Manoplas pesadas de Iwagakure que provocam detonações ao impacto físico.',
      iconName: 'Shield',
      bonusCpsMult: D(1.10),
      bonusClickMult: D(1.45),
      bonusCritMult: D(1.25),
      elementalAffinityReq: 'EARTH',
      elementalBonusClickMult: D(1.15),
      originBossId: 15,
      originBossName: 'Gari da Pedra',
    },
    material: {
      id: 'mat_bakuton_powder',
      name: 'Pó de Argila Explosiva Instável',
      rarity: 'RARE',
      type: 'MATERIAL',
      description: 'Composto altamente inflamável saturado pelo chakra da Liberação de Explosão.',
      iconName: 'Flame',
      baseGoldValue: D(9800),
      originBossId: 15,
      originBossName: 'Gari',
    },
  },
  16: {
    bossId: 16,
    bossName: 'Kushimaru Kuriarare',
    equipment: {
      id: 'eq_nuibari_needle',
      name: 'Nuibari - A Agulha de Costura',
      rarity: 'RARE',
      type: 'WEAPON',
      weaponCategory: 'SWORD',
      description: 'A espada longa e esguia dos Sete Espadachins que perfura e cose múltiplos inimigos.',
      iconName: 'Swords',
      bonusCpsMult: D(1.0),
      bonusClickMult: D(1.50),
      bonusCritChance: 0.08,
      elementalAffinityReq: 'WATER',
      elementalBonusClickMult: D(1.20),
      originBossId: 16,
      originBossName: 'Kushimaru Kuriarare',
    },
    material: {
      id: 'mat_steel_sewing_wire',
      name: 'Fio de Aço Afiado da Névoa',
      rarity: 'RARE',
      type: 'MATERIAL',
      description: 'Cabo metálico ultrafino capaz de decepar membros sem emitir ruído.',
      iconName: 'Feather',
      baseGoldValue: D(13500),
      originBossId: 16,
      originBossName: 'Kushimaru',
    },
  },
  17: {
    bossId: 17,
    bossName: 'Jinpachi Munashi',
    equipment: {
      id: 'eq_shibuki_sword',
      name: 'Shibuki - A Espada de Explosão',
      rarity: 'EPIC',
      type: 'WEAPON',
      weaponCategory: 'HEAVY',
      description: 'A espada gigante acoplada a um cilindro contínuo de pergaminhos explosivos.',
      iconName: 'Swords',
      bonusCpsMult: D(1.0),
      bonusClickMult: D(1.60),
      bonusCritChance: 0.10,
      bonusCritMult: D(1.35),
      originBossId: 17,
      originBossName: 'Jinpachi Munashi',
    },
    material: {
      id: 'mat_endless_bomb_scroll',
      name: 'Rolo de Pergaminhos Explosivos Infinitos',
      rarity: 'EPIC',
      type: 'MATERIAL',
      description: 'Pergaminho reforçado resistente ao fogo com milhares de papéis-bomba gravados.',
      iconName: 'Scroll',
      baseGoldValue: D(18500),
      originBossId: 17,
      originBossName: 'Jinpachi',
    },
  },
  18: {
    bossId: 18,
    bossName: 'Chiyo Reanimada',
    equipment: {
      id: 'eq_infused_sand_gourd',
      name: 'Cabaça de Areia Infundida',
      rarity: 'EPIC',
      type: 'ARMOR',
      description: 'Cabaça de areia ancestral condensada com chakra materno e defesas automáticas impenetráveis.',
      iconName: 'Shield',
      bonusCpsMult: D(1.40), // +40% CPS
      bonusClickMult: D(1.20),
      elementalAffinityReq: 'WIND',
      elementalBonusCpsMult: D(1.20),
      originBossId: 18,
      originBossName: 'Chiyo / Gaara',
    },
    material: {
      id: 'mat_magnetized_sand',
      name: 'Areia Mineral Magnetizada',
      rarity: 'EPIC',
      type: 'MATERIAL',
      description: 'Grânulos metálicos auríferos que reagem a pulsos telecinéticos de chakra.',
      iconName: 'Wind',
      baseGoldValue: D(26000),
      originBossId: 18,
      originBossName: 'Chiyo',
    },
  },
  19: {
    bossId: 19,
    bossName: 'Pakura da Areia',
    equipment: {
      id: 'eq_scorch_solar_orb',
      name: 'Orbe Solar do Estilo Queimadura',
      rarity: 'EPIC',
      type: 'WEAPON',
      weaponCategory: 'BLADE',
      description: 'Esfera ígnea condensada pela Liberação de Calor que evapora a umidade corporal.',
      iconName: 'Swords',
      bonusCpsMult: D(1.0),
      bonusClickMult: D(1.70),
      bonusCritMult: D(1.40),
      bonusCritChance: 0.10,
      elementalAffinityReq: 'FIRE',
      elementalBonusClickMult: D(1.25),
      originBossId: 19,
      originBossName: 'Pakura da Areia',
    },
    material: {
      id: 'mat_scorch_ashes',
      name: 'Cinzas Cristalizadas de Calor Flamejante',
      rarity: 'EPIC',
      type: 'MATERIAL',
      description: 'Cinzas incandescentes que continuam emitindo calor mesmo submergidas em água.',
      iconName: 'Flame',
      baseGoldValue: D(36000),
      originBossId: 19,
      originBossName: 'Pakura',
    },
  },
  20: {
    bossId: 20,
    bossName: 'Fū Yamanaka & Torune Aburame',
    equipment: {
      id: 'eq_nano_beetle_coat',
      name: 'Manto de Insetos Nanométricos da Raiz',
      rarity: 'EPIC',
      type: 'ARMOR',
      description: 'Traje envenenado coberto por colônias de Rinkaichū que anulam o toque inimigo.',
      iconName: 'Shield',
      bonusCpsMult: D(1.55),
      bonusClickMult: D(1.30),
      originBossId: 20,
      originBossName: 'Fū & Torune',
    },
    material: {
      id: 'mat_rinkaichu_colony',
      name: 'Colônia de Insetos Nanométricos Rinkaichū',
      rarity: 'EPIC',
      type: 'MATERIAL',
      description: 'Micro-organismos carnívoros mantidos vivos em receptáculo de vidro escuro.',
      iconName: 'Feather',
      baseGoldValue: D(52000),
      originBossId: 20,
      originBossName: 'Torune',
    },
  },
  21: {
    bossId: 21,
    bossName: 'Guren',
    equipment: {
      id: 'eq_clematis_bone_spear',
      name: 'Lança de Ossos da Clematite',
      rarity: 'LEGENDARY',
      type: 'WEAPON',
      weaponCategory: 'SPEAR',
      description: 'A lança óssea definitiva reforçada com cálcio de alta densidade e elasticidade.',
      iconName: 'Swords',
      bonusCpsMult: D(1.0),
      bonusClickMult: D(1.80), // +80% Clique
      bonusCritChance: 0.12,  // +12% Crítico
      bonusCritMult: D(1.50),
      elementalAffinityReq: 'EARTH',
      elementalBonusClickMult: D(1.20),
      originBossId: 21,
      originBossName: 'Kimimaro / Guren',
    },
    material: {
      id: 'mat_dense_bone_tissue',
      name: 'Fragmento de Tecido Ósseo Denso',
      rarity: 'LEGENDARY',
      type: 'MATERIAL',
      description: 'Fragmento osteológico com rigidez comparável ao diamante puro de batalha.',
      iconName: 'Boxes',
      baseGoldValue: D(78000),
      originBossId: 21,
      originBossName: 'Kimimaro',
    },
  },
  22: {
    bossId: 22,
    bossName: 'Mifune',
    equipment: {
      id: 'eq_kurosawa_katana',
      name: 'Kurosawa - A Espada do Samurai Mestre',
      rarity: 'EPIC',
      type: 'WEAPON',
      weaponCategory: 'SWORD',
      description: 'Lâmina lendária rápida demais para permitir a formação de selos de mão shinobi.',
      iconName: 'Swords',
      bonusCpsMult: D(1.0),
      bonusClickMult: D(1.85),
      bonusCritChance: 0.12,
      bonusCritMult: D(1.45),
      originBossId: 22,
      originBossName: 'Mifune',
    },
    material: {
      id: 'mat_jutsu_cutter_steel',
      name: 'Lâmina de Chakra Afiada do País do Ferro',
      rarity: 'EPIC',
      type: 'MATERIAL',
      description: 'Aço refinado mil vezes em forjas de samurais para condução direta de energia.',
      iconName: 'Boxes',
      baseGoldValue: D(115000),
      originBossId: 22,
      originBossName: 'Mifune',
    },
  },
  23: {
    bossId: 23,
    bossName: 'Shinnō',
    equipment: {
      id: 'eq_dark_chakra_armor',
      name: 'Armadura dos Canais de Chakra Negro',
      rarity: 'EPIC',
      type: 'ARMOR',
      description: 'Armadura bio-orgânica movida pelo chakra escuro alimentado por emoções negativas.',
      iconName: 'Shield',
      bonusCpsMult: D(1.70),
      bonusClickMult: D(1.40),
      originBossId: 23,
      originBossName: 'Shinnō',
    },
    material: {
      id: 'mat_dark_chakra_coil',
      name: 'Bobina de Chakra Escuro Reanimador',
      rarity: 'EPIC',
      type: 'MATERIAL',
      description: 'Artefato antigo do País do Céu que absorve dor e transforma em força física.',
      iconName: 'Sparkles',
      baseGoldValue: D(165000),
      originBossId: 23,
      originBossName: 'Shinnō',
    },
  },
  24: {
    bossId: 24,
    bossName: 'Rasa',
    equipment: {
      id: 'eq_gold_dust_mantle',
      name: 'Manto do Quarto Kazekage - Pó de Ouro',
      rarity: 'EPIC',
      type: 'ARMOR',
      description: 'Manto dourado impérvio saturado com pó de ouro metálico de Sunagakure.',
      iconName: 'Shield',
      bonusCpsMult: D(1.85), // +85% CPS
      bonusClickMult: D(1.25),
      elementalAffinityReq: 'EARTH',
      elementalBonusCpsMult: D(1.25),
      originBossId: 24,
      originBossName: 'Rasa',
    },
    material: {
      id: 'mat_pure_gold_dust',
      name: 'Pó de Ouro Sagrado Magnetizado',
      rarity: 'EPIC',
      type: 'MATERIAL',
      description: 'Ouro refinado de alta densidade utilizado para soterrar o Ichibi Shukaku.',
      iconName: 'Sparkles',
      baseGoldValue: D(250000),
      originBossId: 24,
      originBossName: 'Rasa',
    },
  },
  25: {
    bossId: 25,
    bossName: 'Hiruko',
    equipment: {
      id: 'eq_hiruko_puppet_chassis',
      name: 'Chassi da Marionete Hiruko',
      rarity: 'LEGENDARY',
      type: 'ARMOR',
      description: 'Carcaça mecânica defensiva projetada por Sasori com blindagem imune a toxinas e venenos.',
      iconName: 'Shield',
      bonusCpsMult: D(2.20), // +120% CPS
      bonusClickMult: D(1.30),
      originBossId: 25,
      originBossName: 'Hiruko / Sasori',
    },
    material: {
      id: 'mat_ancient_puppet_core',
      name: 'Núcleo de Marionete Antiga',
      rarity: 'LEGENDARY',
      type: 'MATERIAL',
      description: 'Engrenagem mestra preservada em óleo mineral com séculos de engenharia oculta.',
      iconName: 'Boxes',
      baseGoldValue: D(380000),
      originBossId: 25,
      originBossName: 'Sasori',
    },
  },
  26: {
    bossId: 26,
    bossName: 'Danzō Shimura',
    equipment: {
      id: 'eq_totsuka_spirit_blade',
      name: 'Espada Espiritual de Totsuka',
      rarity: 'MYTHIC',
      type: 'WEAPON',
      weaponCategory: 'SWORD',
      description: 'A lâmina lendária etérea mantida no jarro de saquê capaz de selar eternamente em mundos ilusórios.',
      iconName: 'Swords',
      bonusCpsMult: D(1.0),
      bonusClickMult: D(2.50), // x2.5 no Clique!
      bonusCritChance: 0.15,
      bonusCritMult: D(1.80),
      elementalAffinityReq: 'FIRE',
      elementalBonusClickMult: D(1.50),
      originBossId: 26,
      originBossName: 'Itachi / Danzō',
    },
    material: {
      id: 'mat_amaterasu_crow_feather',
      name: 'Pena de Corvo Envolta em Amaterasu',
      rarity: 'MYTHIC',
      type: 'MATERIAL',
      description: 'Pena mística em chamas negras perpétuas que não se consomem nem se extinguem.',
      iconName: 'Flame',
      baseGoldValue: D(580000),
      originBossId: 26,
      originBossName: 'Itachi',
    },
  },
  27: {
    bossId: 27,
    bossName: 'Muku / Demônio Satori',
    equipment: {
      id: 'eq_paradox_mantle',
      name: 'Manto das Penas Negras da Discórdia',
      rarity: 'LEGENDARY',
      type: 'ARMOR',
      description: 'Vestimenta forjada pelas asas do demônio Satori que lê a intenção assassina adversária.',
      iconName: 'Shield',
      bonusCpsMult: D(2.40),
      bonusClickMult: D(1.50),
      originBossId: 27,
      originBossName: 'Muku / Satori',
    },
    material: {
      id: 'mat_satori_black_feather',
      name: 'Pena Negra do Demônio Satori',
      rarity: 'LEGENDARY',
      type: 'MATERIAL',
      description: 'Pluma etérea que emite sussurros da temível Caixa do Paraíso Supremo.',
      iconName: 'Feather',
      baseGoldValue: D(850000),
      originBossId: 27,
      originBossName: 'Satori',
    },
  },
  28: {
    bossId: 28,
    bossName: 'Mukade',
    equipment: {
      id: 'eq_roran_chassis',
      name: 'Carcaça de Marionete de Rōran',
      rarity: 'LEGENDARY',
      type: 'ARMOR',
      description: 'Estrutura colossal de titânio acionada pelas linhas de leilão temporal de Ryūmyaku.',
      iconName: 'Shield',
      bonusCpsMult: D(2.60),
      bonusClickMult: D(1.55),
      originBossId: 28,
      originBossName: 'Mukade',
    },
    material: {
      id: 'mat_ryumyaku_core',
      name: 'Núcleo de Ryūmyaku de Rōran',
      rarity: 'LEGENDARY',
      type: 'MATERIAL',
      description: 'Condensado cristalino de chakra temporal infinito das ruínas milenares.',
      iconName: 'Sparkles',
      baseGoldValue: D(1250000),
      originBossId: 28,
      originBossName: 'Mukade',
    },
  },
  29: {
    bossId: 29,
    bossName: 'Kinkaku & Ginkaku',
    equipment: {
      id: 'eq_bashosen_fan',
      name: 'Bashōsen - O Leque de Folha de Bananeira',
      rarity: 'LEGENDARY',
      type: 'WEAPON',
      weaponCategory: 'HEAVY',
      description: 'O tesouro lendário do Sábio dos Seis Caminhos capaz de liberar qualquer uma das 5 naturezas.',
      iconName: 'Swords',
      bonusCpsMult: D(2.40),
      bonusClickMult: D(1.50),
      bonusCritChance: 0.12,
      elementalAffinityReq: 'WIND',
      elementalBonusCpsMult: D(1.30),
      originBossId: 29,
      originBossName: 'Kinkaku & Ginkaku',
    },
    material: {
      id: 'mat_golden_clarity_rope',
      name: 'Corda da Claridade Dourada',
      rarity: 'LEGENDARY',
      type: 'MATERIAL',
      description: 'Corda mágica ancestral de Rikudō Sennin que extrai e grava palavras de alma.',
      iconName: 'Feather',
      baseGoldValue: D(1900000),
      originBossId: 29,
      originBossName: 'Kinkaku',
    },
  },
  30: {
    bossId: 30,
    bossName: 'Terceiro Raikage',
    equipment: {
      id: 'eq_raiton_four_finger_spear',
      name: 'Lança Raiton dos Quatro Dedos',
      rarity: 'MYTHIC',
      type: 'WEAPON',
      weaponCategory: 'HEAVY',
      description: 'A lança corporal indomável do Terceiro Raikage: perfura montanhas e blindagens colossais.',
      iconName: 'Swords',
      bonusCpsMult: D(1.0),
      bonusClickMult: D(2.80),
      bonusCritChance: 0.15,
      bonusCritMult: D(1.60),
      elementalAffinityReq: 'LIGHTNING',
      elementalBonusClickMult: D(3.0), // x3.0 no clique se Raio!
      originBossId: 30,
      originBossName: 'Terceiro Raikage',
    },
    material: {
      id: 'mat_black_lightning_residue',
      name: 'Resíduo de Relâmpago Negro',
      rarity: 'MYTHIC',
      type: 'MATERIAL',
      description: 'Plasma iônico de cor ébano que ferve a atmosfera ao redor de sua estrutura.',
      iconName: 'Zap',
      baseGoldValue: D(2900000),
      originBossId: 30,
      originBossName: 'Terceiro Raikage',
    },
  },
  31: {
    bossId: 31,
    bossName: 'Muu',
    equipment: {
      id: 'eq_dust_release_bandages',
      name: 'Bandagens do Segundo Tsuchikage',
      rarity: 'LEGENDARY',
      type: 'ARMOR',
      description: 'Bandagens cirúrgicas que apagam a assinatura de chakra de seu portador por completo.',
      iconName: 'Shield',
      bonusCpsMult: D(2.70),
      bonusClickMult: D(1.60),
      elementalAffinityReq: 'EARTH',
      elementalBonusCpsMult: D(1.35),
      originBossId: 31,
      originBossName: 'Muu',
    },
    material: {
      id: 'mat_atomic_dust_shard',
      name: 'Fragmento Atômico do Estilo Poeira',
      rarity: 'LEGENDARY',
      type: 'MATERIAL',
      description: 'Estrutura geométrica tridimensional microscópica da Liberação de Poeira.',
      iconName: 'Boxes',
      baseGoldValue: D(4200000),
      originBossId: 31,
      originBossName: 'Muu',
    },
  },
  32: {
    bossId: 32,
    bossName: 'Hanzō da Salamandra',
    equipment: {
      id: 'eq_ibuse_scythe',
      name: 'Kusarigama da Salamandra Negra',
      rarity: 'LEGENDARY',
      type: 'WEAPON',
      weaponCategory: 'BLADE',
      description: 'A foice encadeada impregnada com o veneno mortal inalável de Ibuse.',
      iconName: 'Swords',
      bonusCpsMult: D(1.0),
      bonusClickMult: D(2.70),
      bonusCritChance: 0.15,
      bonusCritMult: D(1.50),
      elementalAffinityReq: 'WATER',
      elementalBonusClickMult: D(1.40),
      originBossId: 32,
      originBossName: 'Hanzō da Salamandra',
    },
    material: {
      id: 'mat_ibuse_poison_sac',
      name: 'Glândula de Veneno Puro de Ibuse',
      rarity: 'LEGENDARY',
      type: 'MATERIAL',
      description: 'Saco venenoso intacto contendo toxina lendária da grande salamandra.',
      iconName: 'Sparkles',
      baseGoldValue: D(6300000),
      originBossId: 32,
      originBossName: 'Hanzō',
    },
  },
  33: {
    bossId: 33,
    bossName: 'Gengetsu Hōzuki',
    equipment: {
      id: 'eq_mirage_oil_robe',
      name: 'Manto de Óleo e Miragem do Segundo Mizukage',
      rarity: 'LEGENDARY',
      type: 'ARMOR',
      description: 'Traje escorregadio recoberto por óleo que reflete a luz criando miragens táteis.',
      iconName: 'Shield',
      bonusCpsMult: D(2.90),
      bonusClickMult: D(1.65),
      elementalAffinityReq: 'WATER',
      elementalBonusCpsMult: D(1.40),
      originBossId: 33,
      originBossName: 'Gengetsu Hōzuki',
    },
    material: {
      id: 'mat_mirage_clam_oil',
      name: 'Gotícula de Óleo do Marfim Miragem',
      rarity: 'LEGENDARY',
      type: 'MATERIAL',
      description: 'Líquido etéreo destilado pelo molusco gigante que distorce as percepções visuais.',
      iconName: 'Sparkles',
      baseGoldValue: D(9500000),
      originBossId: 33,
      originBossName: 'Gengetsu',
    },
  },
  34: {
    bossId: 34,
    bossName: 'Mōryō',
    equipment: {
      id: 'eq_moryo_dark_armor',
      name: 'Armadura do Demônio do Submundo Mōryō',
      rarity: 'LEGENDARY',
      type: 'ARMOR',
      description: 'Carapaça de chakra demoníaco que consome a vitalidade circundante e alimenta o portador.',
      iconName: 'Shield',
      bonusCpsMult: D(3.10),
      bonusClickMult: D(1.70),
      originBossId: 34,
      originBossName: 'Mōryō',
    },
    material: {
      id: 'mat_demon_sealing_stone',
      name: 'Pedra Seladora do Submundo',
      rarity: 'LEGENDARY',
      type: 'MATERIAL',
      description: 'Fragmento do altar de pedra que manteve o espírito de Mōryō selado por milênios.',
      iconName: 'Mountain',
      baseGoldValue: D(14500000),
      originBossId: 34,
      originBossName: 'Mōryō',
    },
  },
  35: {
    bossId: 35,
    bossName: 'Shin Uchiha',
    equipment: {
      id: 'eq_shin_mangekyo_blades',
      name: 'Lâminas Telecinéticas com Mangekyō',
      rarity: 'MYTHIC',
      type: 'WEAPON',
      weaponCategory: 'BLADE',
      description: 'Escalpelos voadores manipulados mentalmente pelo dōjutsu Mangekyō Sharingan.',
      iconName: 'Swords',
      bonusCpsMult: D(1.0),
      bonusClickMult: D(3.20),
      bonusCritChance: 0.20,
      bonusCritMult: D(1.80),
      originBossId: 35,
      originBossName: 'Shin Uchiha',
    },
    material: {
      id: 'mat_synthetic_mangekyo_eye',
      name: 'Olho Mangekyō Sintético Calibrado',
      rarity: 'MYTHIC',
      type: 'MATERIAL',
      description: 'Globo ocular geneticamente clonado com padrões avançados de percepção espacial.',
      iconName: 'Sparkles',
      baseGoldValue: D(23000000),
      originBossId: 35,
      originBossName: 'Shin Uchiha',
    },
  },
  36: {
    bossId: 36,
    bossName: 'Menma Uzumaki',
    equipment: {
      id: 'eq_black_nine_tails_cloak',
      name: 'Manto das Nove Bestas Mascaradas',
      rarity: 'MYTHIC',
      type: 'ARMOR',
      description: 'Manto de chakra denso da Kurama Negra emanando a técnica Dai Rasenringu.',
      iconName: 'Shield',
      bonusCpsMult: D(3.60),
      bonusClickMult: D(2.0),
      bonusCritChance: 0.15,
      originBossId: 36,
      originBossName: 'Menma Uzumaki',
    },
    material: {
      id: 'mat_dark_kurama_essence',
      name: 'Essência de Kurama Negra',
      rarity: 'MYTHIC',
      type: 'MATERIAL',
      description: 'Gotícula condensada de ódio puro e chakra bestial do mundo dos espelhos.',
      iconName: 'Flame',
      baseGoldValue: D(37000000),
      originBossId: 36,
      originBossName: 'Menma',
    },
  },
  37: {
    bossId: 37,
    bossName: 'Toneri Otsutsuki',
    equipment: {
      id: 'eq_tenseigan_silver_blade',
      name: 'Espada de Reencarnação de Prata do Tenseigan',
      rarity: 'MYTHIC',
      type: 'WEAPON',
      weaponCategory: 'SWORD',
      description: 'Lâmina de luz pura impulsionada pelo manto do Tenseigan capaz de partir a Lua.',
      iconName: 'Swords',
      bonusCpsMult: D(1.0),
      bonusClickMult: D(3.80),
      bonusCritChance: 0.22,
      bonusCritMult: D(2.0),
      originBossId: 37,
      originBossName: 'Toneri Otsutsuki',
    },
    material: {
      id: 'mat_lunar_tenseigan_crystal',
      name: 'Cristal Lunar do Tenseigan Supremo',
      rarity: 'MYTHIC',
      type: 'MATERIAL',
      description: 'Minério estelar do castelo lunar infundido pelo dōjutsu dos descendentes de Hamura.',
      iconName: 'Sparkles',
      baseGoldValue: D(62000000),
      originBossId: 37,
      originBossName: 'Toneri',
    },
  },
  38: {
    bossId: 38,
    bossName: 'Urashiki Otsutsuki',
    equipment: {
      id: 'eq_temporal_fishing_rod',
      name: 'Vara de Pesca Temporal de Chakra Vermelho',
      rarity: 'MYTHIC',
      type: 'WEAPON',
      weaponCategory: 'SPEAR',
      description: 'Vara celestial capaz de perfurar dimensões e fisgar o chakra diretamente do núcleo do alvo.',
      iconName: 'Swords',
      bonusCpsMult: D(1.0),
      bonusClickMult: D(4.0),
      bonusCritChance: 0.20,
      bonusCritMult: D(2.20),
      originBossId: 38,
      originBossName: 'Urashiki Otsutsuki',
    },
    material: {
      id: 'mat_stolen_chakra_orb',
      name: 'Isca de Chakra Temporal Roubado',
      rarity: 'MYTHIC',
      type: 'MATERIAL',
      description: 'Frasco celestial repleto de técnicas shinobis roubadas ao longo das eras.',
      iconName: 'Sparkles',
      baseGoldValue: D(105000000),
      originBossId: 38,
      originBossName: 'Urashiki',
    },
  },
  39: {
    bossId: 39,
    bossName: 'Kinshiki Otsutsuki',
    equipment: {
      id: 'eq_crimson_forge_axe',
      name: 'Machado Titânico da Forja Carmesim',
      rarity: 'MYTHIC',
      type: 'WEAPON',
      weaponCategory: 'HEAVY',
      description: 'Arma pesada forjada instantaneamente a partir de chakra incandescente puro pelos céus.',
      iconName: 'Swords',
      bonusCpsMult: D(1.0),
      bonusClickMult: D(4.5),
      bonusCritChance: 0.25,
      bonusCritMult: D(2.50),
      originBossId: 39,
      originBossName: 'Kinshiki Otsutsuki',
    },
    material: {
      id: 'mat_primordial_forged_ingot',
      name: 'Lingote Primordial de Chakra Forjado',
      rarity: 'MYTHIC',
      type: 'MATERIAL',
      description: 'Fragmento do arsenal celestial com peso que distorce a gravidade ao redor.',
      iconName: 'Boxes',
      baseGoldValue: D(185000000),
      originBossId: 39,
      originBossName: 'Kinshiki',
    },
  },
  40: {
    bossId: 40,
    bossName: 'Isshiki Otsutsuki',
    equipment: {
      id: 'eq_daikokuten_spear',
      name: 'Lança Temporal de Daikokuten',
      rarity: 'MYTHIC',
      type: 'WEAPON',
      weaponCategory: 'HEAVY',
      description: 'Lança extraída de dimensões congeladas no tempo através do dōjutsu Daikokuten de Isshiki.',
      iconName: 'Swords',
      bonusCpsMult: D(4.0), // +300% CPS global
      bonusClickMult: D(5.0), // x5.0 Clique
      bonusCritChance: 0.30,
      bonusCritMult: D(3.0),
      originBossId: 40,
      originBossName: 'Isshiki Otsutsuki',
    },
    material: {
      id: 'mat_temporal_cube',
      name: 'Cubo Negro de Compressão Temporal',
      rarity: 'MYTHIC',
      type: 'MATERIAL',
      description: 'Monólito dimensional de Daikokuten que bloqueia assinaturas sensoriais de chakra.',
      iconName: 'Boxes',
      baseGoldValue: D(300000000),
      originBossId: 40,
      originBossName: 'Isshiki Otsutsuki',
    },
  },
};

/**
 * Procedural fallback for boss IDs outside 1-40
 */
export function getBossLootDefinition(bossId: number): BossLootDefinition {
  if (BOSS_LOOT_CATALOG[bossId]) {
    return BOSS_LOOT_CATALOG[bossId];
  }

  // Generative fallback for endgame or custom bosses (41+)
  const rarity: ItemRarity = bossId > 75 ? 'MYTHIC' : bossId > 45 ? 'LEGENDARY' : 'EPIC';
  const multCps = D(1 + bossId * 0.05);
  const multClick = D(1 + bossId * 0.08);

  return {
    bossId,
    bossName: `Chefe Imperial #${bossId}`,
    equipment: {
      id: `eq_procedural_boss_${bossId}`,
      name: `Relíquia Dimensional de Boss #${bossId}`,
      rarity,
      type: bossId % 2 === 0 ? 'WEAPON' : 'ARMOR',
      weaponCategory: 'SWORD',
      description: `Artefato raro deixado após a queda do colossal chefe da fase #${bossId}.`,
      iconName: bossId % 2 === 0 ? 'Swords' : 'Shield',
      bonusCpsMult: multCps,
      bonusClickMult: multClick,
      bonusCritChance: 0.15,
      bonusCritMult: D(1.5),
      originBossId: bossId,
      originBossName: `Chefe #${bossId}`,
    },
    material: {
      id: `mat_procedural_boss_${bossId}`,
      name: `Essência Astral de Boss #${bossId}`,
      rarity,
      type: 'MATERIAL',
      description: `Material de alta cotação mercadológica recuperado da fase #${bossId}.`,
      iconName: 'Sparkles',
      baseGoldValue: D(1000000).mul(bossId),
      originBossId: bossId,
      originBossName: `Chefe #${bossId}`,
    },
  };
}

export interface BossLootRollResult {
  equipmentDrop: EquipmentItem | null;
  farmMaterial: FarmMaterialItem;
  dropProbability: number;
  rolledProbability: number;
}

/**
 * Executa a rolagem estocástica de saque com base no ID do chefe.
 */
export function rollBossLoot(bossId: number): BossLootRollResult {
  const definition = getBossLootDefinition(bossId);
  const dropProb = calculateBossDropProbability(bossId);
  const roll = Math.random();

  const equipmentDrop = roll < dropProb ? { ...definition.equipment } : null;

  // Farm materials drop 100% with 1 to 5 random units
  const stackCount = Math.floor(Math.random() * 5) + 1;
  const farmMaterial: FarmMaterialItem = {
    ...definition.material,
    stackCount,
  };

  return {
    equipmentDrop,
    farmMaterial,
    dropProbability: dropProb,
    rolledProbability: roll,
  };
}
