import Decimal from 'break_infinity.js';
import { ForgeRecipe } from '../types/forge';

export const FORGE_RECIPES_CATALOG: ForgeRecipe[] = [
  {
    id: 'forge_kunai_hiraishin',
    name: 'Kunai de Três Pontas do Hiraishin',
    description: 'Arma de arremesso balanceada com o kanji de teletransporte instantâneo de Minato.',
    lore: 'Forjada com liga leve de chakra, permite manobras relâmpago de alta precisão em combate.',
    costFragments: 15,
    rarity: 'RARE',
    slotType: 'WEAPON_RANGED',
    iconName: 'Crosshair',
    requiredRankTier: 0,
    badge: 'Relâmpago Dourado',
    resultItem: {
      id: 'forge_kunai_hiraishin',
      name: 'Kunai de Três Pontas do Hiraishin',
      description: 'Arma de arremesso balanceada com o kanji de teletransporte instantâneo.',
      rarity: 'RARE',
      type: 'WEAPON_RANGED',
      iconName: 'Crosshair',
      bonusCpsMult: new Decimal(1.2),
      bonusClickMult: new Decimal(1.4),
      bonusCritChance: 0.03,
      bonusCritMult: new Decimal(1.25),
    },
  },
  {
    id: 'forge_asuma_blades',
    name: 'Lâminas de Trincheira Acheladas de Asuma',
    description: 'Par de soqueiras com lâminas serrilhadas que canalizam chakra elemental de vento afiado.',
    lore: 'O aço especial absorve a natureza do fluxo de chakra, cortando rochas como se fossem manteiga.',
    costFragments: 35,
    rarity: 'RARE',
    slotType: 'WEAPON_MELEE',
    iconName: 'Swords',
    requiredRankTier: 1,
    badge: 'Vontade do Vento',
    resultItem: {
      id: 'forge_asuma_blades',
      name: 'Lâminas de Trincheira Acheladas de Asuma',
      description: 'Lâminas que canalizam o chakra de vento ampliando a penetração de corte.',
      rarity: 'RARE',
      type: 'WEAPON_MELEE',
      iconName: 'Swords',
      bonusCpsMult: new Decimal(1.45),
      bonusClickMult: new Decimal(1.6),
      bonusCritChance: 0.05,
      bonusCritMult: new Decimal(1.3),
    },
  },
  {
    id: 'forge_kubikiribocho',
    name: 'Espada Decapitadora (Kubikiribōchō)',
    description: 'A colossal lâmina de corte dos Sete Espadachins da Névoa que se regenera com o ferro do sangue.',
    lore: 'Uma espada imensa capaz de ceifar esquadrões inteiros com um único arco de movimento brutal.',
    costFragments: 75,
    rarity: 'EPIC',
    slotType: 'WEAPON_MELEE',
    iconName: 'Swords',
    requiredRankTier: 2,
    badge: 'Espadachins da Névoa',
    resultItem: {
      id: 'forge_kubikiribocho',
      name: 'Espada Decapitadora (Kubikiribōchō)',
      description: 'A colossal lâmina dos Espadachins da Névoa com capacidade regenerativa.',
      rarity: 'EPIC',
      type: 'WEAPON_MELEE',
      iconName: 'Swords',
      bonusCpsMult: new Decimal(1.85),
      bonusClickMult: new Decimal(2.0),
      bonusCritChance: 0.08,
      bonusCritMult: new Decimal(1.5),
    },
  },
  {
    id: 'forge_raikage_vest',
    name: 'Colete de Malha Blindado do Raikage',
    description: 'Armadura corporal com ligas condutoras de Raiton que eletrifica a defesa do usuário.',
    lore: 'Utilizada pela guarda do Raikage para resistir a investidas frontais e aumentar o vigor neuromuscular.',
    costFragments: 150,
    rarity: 'EPIC',
    slotType: 'CHESTPLATE',
    iconName: 'Shield',
    requiredRankTier: 3,
    badge: 'Manto do Trovão',
    resultItem: {
      id: 'forge_raikage_vest',
      name: 'Colete de Malha Blindado do Raikage',
      description: 'Armadura de malha com ligas de Raiton condutoras de proteção extrema.',
      rarity: 'EPIC',
      type: 'CHESTPLATE',
      iconName: 'Shield',
      bonusCpsMult: new Decimal(2.2),
      bonusClickMult: new Decimal(1.8),
      bonusCritChance: 0.06,
      bonusCritMult: new Decimal(1.4),
    },
  },
  {
    id: 'forge_samehada',
    name: 'Samehada Viva (Pele de Tubarão Espiritual)',
    description: 'Lâmina simbiótica viva que devora o chakra de inimigos e o transfere diretamente ao portador.',
    lore: 'A mais aterrorizante das espadas da névoa. Rasga em vez de cortar e possui consciência própria faminta.',
    costFragments: 280,
    rarity: 'LEGENDARY',
    slotType: 'WEAPON_MELEE',
    iconName: 'Swords',
    requiredRankTier: 4,
    badge: 'Devoradora de Chakra',
    resultItem: {
      id: 'forge_samehada',
      name: 'Samehada Viva (Pele de Tubarão Espiritual)',
      description: 'Lâmina senciente que devora reservas de energia amplificando o fluxo orgânico.',
      rarity: 'LEGENDARY',
      type: 'WEAPON_MELEE',
      iconName: 'Swords',
      bonusCpsMult: new Decimal(3.5),
      bonusClickMult: new Decimal(3.0),
      bonusCritChance: 0.12,
      bonusCritMult: new Decimal(2.0),
    },
  },
  {
    id: 'forge_gunbai_madara',
    name: 'Leque Gunbai de Guerra de Madara',
    description: 'Leque ancestral sagrado esculpido a partir da madeira da Árvore Divina com correntes de retenção.',
    lore: 'Reflete projéteis inimigos devolvendo seu impacto em forma de rajadas furiosas de vento e fogo.',
    costFragments: 500,
    rarity: 'LEGENDARY',
    slotType: 'WEAPON_RANGED',
    iconName: 'Crosshair',
    requiredRankTier: 5,
    badge: 'Legado de Madara',
    resultItem: {
      id: 'forge_gunbai_madara',
      name: 'Leque Gunbai de Guerra de Madara',
      description: 'Leque cerimonial da Árvore Divina capaz de repelir e redirecionar tempestades de energia.',
      rarity: 'LEGENDARY',
      type: 'WEAPON_RANGED',
      iconName: 'Crosshair',
      bonusCpsMult: new Decimal(5.5),
      bonusClickMult: new Decimal(4.5),
      bonusCritChance: 0.15,
      bonusCritMult: new Decimal(2.5),
    },
  },
  {
    id: 'forge_totsuka_blade',
    name: 'Espada Totsuka Divina (Sakegari no Tsurugi)',
    description: 'Arma astral e etérea empunhada pelo Susanoo de Itachi, capaz de selar almas no mundo dos bêbados.',
    lore: 'Uma lâmina sem forma física contida em uma cabaça sagrada que sela qualquer ameaça para a eternidade.',
    costFragments: 900,
    rarity: 'MYTHIC',
    slotType: 'WEAPON_MELEE',
    iconName: 'Sparkles',
    requiredRankTier: 6,
    badge: 'Artefato Mítico Susanoo',
    resultItem: {
      id: 'forge_totsuka_blade',
      name: 'Espada Totsuka Divina (Sakegari no Tsurugi)',
      description: 'Espada espiritual que sela o chakra universal e transcende o plano físico.',
      rarity: 'MYTHIC',
      type: 'WEAPON_MELEE',
      iconName: 'Sparkles',
      bonusCpsMult: new Decimal(10.0),
      bonusClickMult: new Decimal(8.0),
      bonusCritChance: 0.2,
      bonusCritMult: new Decimal(3.5),
    },
  },
  {
    id: 'forge_nunoboko_sword',
    name: 'Lâmina Sagrada de Nunoboko do Rikudō',
    description: 'A espada em hélice de DNA usada por Hagoromo Ōtsutsuki para moldar a própria geografia do planeta.',
    lore: 'Materializada puramente a partir de esferas da busca da verdade (Gudōdama), comanda a matéria primordial.',
    costFragments: 1800,
    rarity: 'MYTHIC',
    slotType: 'WEAPON_MELEE',
    iconName: 'Sparkles',
    requiredRankTier: 7,
    badge: 'Criação do Mundo',
    resultItem: {
      id: 'forge_nunoboko_sword',
      name: 'Lâmina Sagrada de Nunoboko do Rikudō',
      description: 'Lâmina em hélice divina que dita as leis de manifestação e aniquilação do universo.',
      rarity: 'MYTHIC',
      type: 'WEAPON_MELEE',
      iconName: 'Sparkles',
      bonusCpsMult: new Decimal(25.0),
      bonusClickMult: new Decimal(18.0),
      bonusCritChance: 0.3,
      bonusCritMult: new Decimal(5.0),
    },
  },
];
