import { D } from '../engine/BigNumber';
import { TechniqueUpgrade, GeneratorMilestoneEffect } from '../types/upgrades';

export const GENERATOR_MILESTONE_LEVELS = [25, 50, 100, 200, 300, 500] as const;

/**
 * Retorna os bônus e insígnia de marco acumulados pelo nível de um gerador
 */
export function getGeneratorMilestoneEffects(level: number): GeneratorMilestoneEffect {
  let mult = D(1);
  let discount = 0;
  let clickRatio = 0;
  let tierName = 'Iniciado';
  let badgeColor = 'text-zinc-500 border-zinc-700/60 bg-zinc-800/40';
  let nextMilestoneLevel: number | null = 25;

  if (level >= 25) {
    mult = mult.mul(1.5);
    tierName = 'Bronze';
    badgeColor = 'text-amber-500 border-amber-700/60 bg-amber-950/40';
    nextMilestoneLevel = 50;
  }
  if (level >= 50) {
    mult = mult.mul(1.5);
    discount += 0.03;
    tierName = 'Prata';
    badgeColor = 'text-zinc-300 border-zinc-400/60 bg-zinc-800/50';
    nextMilestoneLevel = 100;
  }
  if (level >= 100) {
    mult = mult.mul(2.0);
    clickRatio += 0.0008;
    tierName = 'Ouro';
    badgeColor = 'text-amber-300 border-amber-500/60 bg-amber-900/40';
    nextMilestoneLevel = 200;
  }
  if (level >= 200) {
    mult = mult.mul(2.5);
    tierName = 'Platina';
    badgeColor = 'text-cyan-300 border-cyan-500/60 bg-cyan-950/40';
    nextMilestoneLevel = 300;
  }
  if (level >= 300) {
    mult = mult.mul(3.0);
    tierName = 'Diamante';
    badgeColor = 'text-indigo-300 border-indigo-500/60 bg-indigo-950/40';
    nextMilestoneLevel = 500;
  }
  if (level >= 500) {
    mult = mult.mul(5.0);
    tierName = 'Rikudou';
    badgeColor = 'text-fuchsia-300 border-fuchsia-500/60 bg-fuchsia-950/40';
    nextMilestoneLevel = null;
  }

  return {
    cpsMultiplier: mult,
    costDiscount: discount,
    clickCpsRatio: clickRatio,
    tierName,
    badgeColor,
    nextMilestoneLevel,
  };
}

export const TECHNIQUE_UPGRADES: TechniqueUpgrade[] = [
  // =========================================================================
  // 1. TAIJUTSU & SELOS (CLIQUE ATIVO) - LINHAGENS V1, V2, V3 & ESPECIAIS
  // =========================================================================

  // --- Linhagem Furacão da Folha ---
  {
    id: 'leaf_hurricane',
    name: 'Furacão da Folha (Konoha Senpū)',
    category: 'taijutsu',
    description: 'Golpe rotacional veloz. Multiplica o poder de clique manual em +100% (2x).',
    cost: D(1500),
    icon: 'zap',
    effectType: 'click_multiplier',
    multiplier: 2.0,
    tier: 1,
    seriesId: 'leaf_hurricane',
  },
  {
    id: 'leaf_great_hurricane_v2',
    name: 'Grande Furacão da Folha (Konoha Daisenpū)',
    category: 'taijutsu',
    description: 'Sucessão feroz de rasteiras e giros aéreos. Multiplica o clique manual em 3.5x.',
    cost: D(120000),
    icon: 'zap',
    effectType: 'click_multiplier',
    multiplier: 3.5,
    tier: 2,
    seriesId: 'leaf_hurricane',
    requiredUpgradeId: 'leaf_hurricane',
  },
  {
    id: 'leaf_dragon_whirlwind_v3',
    name: 'Redemoinho do Dragão da Juventude',
    category: 'taijutsu',
    description: 'Tufão rodopiante com o rugido do dragão verde de Konoha. Multiplica o clique por 6x.',
    cost: D(15000000),
    icon: 'flame',
    effectType: 'click_multiplier',
    multiplier: 6.0,
    tier: 3,
    seriesId: 'leaf_hurricane',
    requiredUpgradeId: 'leaf_great_hurricane_v2',
  },

  // --- Linhagem Rasengan ---
  {
    id: 'rasengan_mastery',
    name: 'Mestria do Rasengan Esférico',
    category: 'taijutsu',
    description: 'Chakra condensado em rotação absoluta contínua. Dobra o poder do clique manual (2x).',
    cost: D(90000000),
    icon: 'orbit',
    effectType: 'click_multiplier',
    multiplier: 2.0,
    tier: 1,
    seriesId: 'rasengan',
  },
  {
    id: 'rasengan_oodama_v2',
    name: 'Ōdama Rasengan (Grande Esfera Espiral)',
    category: 'taijutsu',
    description: 'Esfera espiral colossal de alta densidade destrutiva. Multiplica o poder de clique por 4x.',
    cost: D(4500000000),
    icon: 'orbit',
    effectType: 'click_multiplier',
    multiplier: 4.0,
    tier: 2,
    seriesId: 'rasengan',
    requiredUpgradeId: 'rasengan_mastery',
  },
  {
    id: 'rasen_shuriken_v3',
    name: 'Fūton: Rasenshuriken dos Seis Caminhos',
    category: 'taijutsu',
    description: 'Vórtice celular de agulhas microscópicas de vento. Multiplica clique por 8x e adiciona +1.0% de CPS ao clique.',
    cost: D(250000000000),
    icon: 'orbit',
    effectType: 'click_multiplier',
    multiplier: 8.0,
    tier: 3,
    seriesId: 'rasengan',
    requiredUpgradeId: 'rasengan_oodama_v2',
  },

  // --- Linhagem Hiraishin ---
  {
    id: 'flying_raijin_slice',
    name: 'Corte do Deus Voador do Trovão (Hiraishin Giri)',
    category: 'taijutsu',
    description: 'Salto dimensional instantâneo entre marcas de fórmula. Multiplica o poder de clique em 2.5x.',
    cost: D(450000000),
    icon: 'zap',
    effectType: 'click_multiplier',
    multiplier: 2.5,
    tier: 1,
    seriesId: 'hiraishin',
  },
  {
    id: 'flying_raijin_guiding_thunder_v2',
    name: 'Hiraishin: Trovão Guia Espaço-Temporal',
    category: 'taijutsu',
    description: 'Barreira dimensional que dobra o tecido espacial. Multiplica o poder do clique em 5x.',
    cost: D("1800000000000"),
    icon: 'zap',
    effectType: 'click_multiplier',
    multiplier: 5.0,
    tier: 2,
    seriesId: 'hiraishin',
    requiredUpgradeId: 'flying_raijin_slice',
  },
  {
    id: 'flying_raijin_jikuukan_v3',
    name: 'Hiraishin: Fenda Dimensional Infinita',
    category: 'taijutsu',
    description: 'Salto espaço-temporal onipresente em qualquer coordenada. Multiplica o poder de clique manual por 12x.',
    cost: D("75000000000000"),
    icon: 'zap',
    effectType: 'click_multiplier',
    multiplier: 12.0,
    tier: 3,
    seriesId: 'hiraishin',
    requiredUpgradeId: 'flying_raijin_guiding_thunder_v2',
  },

  // --- Linhagem Oito Portões Internos ---
  {
    id: 'morning_peacock',
    name: 'Pavão da Manhã (Asakujaku)',
    category: 'taijutsu',
    description: 'Sexto Portão da Visão aberto. Punhos velozes que incendeiam o atrito do ar. Triplica o poder do clique (3x).',
    cost: D(1500000000),
    icon: 'flame',
    effectType: 'click_multiplier',
    multiplier: 3.0,
    tier: 1,
    seriesId: 'hachimon',
  },
  {
    id: 'daytime_tiger',
    name: 'Tigre Diurno (Hirudora)',
    category: 'taijutsu',
    description: 'Sétimo Portão da Maravilha. Onda de choque compactada de ar. Converte +1.0% do CPS^0.65 ao clique.',
    cost: D(75000000000),
    icon: 'target',
    effectType: 'click_cps_ratio',
    multiplier: 0.010,
    tier: 2,
    seriesId: 'hachimon',
    requiredUpgradeId: 'morning_peacock',
  },
  {
    id: 'night_guy_dragon',
    name: 'Dragão Noturno do Oitavo Portão (Yagai Supremo)',
    category: 'taijutsu',
    description: 'Oitavo Portão da Morte liberado: Dragão Vermelho que distorce o espaço. Multiplica clique manual por 10x.',
    cost: D("3500000000000000"),
    icon: 'flame',
    effectType: 'click_multiplier',
    multiplier: 10.0,
    tier: 3,
    seriesId: 'hachimon',
    requiredUpgradeId: 'daytime_tiger',
  },

  // --- Técnicas Ativas de Suporte Shinobi ---
  {
    id: 'bandana_genin',
    name: 'Bandana de Gennin Protetora',
    category: 'taijutsu',
    description: 'Símbolo de honra e firmeza. +50% de poder de clique manual.',
    cost: D(25000),
    icon: 'award',
    effectType: 'click_multiplier',
    multiplier: 1.5,
    tier: 1,
  },
  {
    id: 'lion_combo',
    name: 'Combo do Leão (Shishi Rendan)',
    category: 'taijutsu',
    description: 'Sequência aérea devastadora. Aumenta a chance de acerto crítico em +5%.',
    cost: D(180000),
    icon: 'crosshair',
    effectType: 'crit_chance',
    multiplier: 0.05,
    tier: 1,
  },
  {
    id: 'blade_storm',
    name: 'Tempestade de Lâminas Shinobi',
    category: 'taijutsu',
    description: 'Saraivada de armas cortantes. +30% de poder de clique manual.',
    cost: D(30000000),
    icon: 'swords',
    effectType: 'click_multiplier',
    multiplier: 1.3,
    tier: 1,
  },
  {
    id: 'night_guy',
    name: 'Guy Noturno (Yagai Redemoinho)',
    category: 'taijutsu',
    description: 'O ápice da juventude que distorce o espaço. Multiplica o multiplicador de crítico por 2.5x.',
    cost: D("5000000000000"),
    icon: 'flame',
    effectType: 'crit_multiplier',
    multiplier: 2.5,
    tier: 2,
  },
  {
    id: 'truth_seeking_orbs',
    name: 'Esferas da Busca da Verdade (Gudōdama)',
    category: 'taijutsu',
    description: 'Fluidez de todas as naturezas combinadas. Triplica o dano de clique manual (3x).',
    cost: D(25000000000),
    icon: 'sparkles',
    effectType: 'click_multiplier',
    multiplier: 3.0,
    tier: 2,
  },

  // =========================================================================
  // 2. NINJUTSU & INVOCAÇÃO (PRODUÇÃO PASSIVA / CPS) - LINHAGENS V1, V2, V3
  // =========================================================================

  // --- Linhagem Kage Bunshin ---
  {
    id: 'shadow_clone_scroll',
    name: 'Pergaminho de Clones das Sombras',
    category: 'ninjutsu',
    description: 'Distribuição simétrica de fluxo vital. Clones das Sombras produzem +50% CPS.',
    cost: D(7500),
    icon: 'users',
    effectType: 'generator_multiplier',
    multiplier: 1.5,
    targetGenerator: 'shadow_clone',
    tier: 1,
    seriesId: 'kage_bunshin',
  },
  {
    id: 'tajuu_shadow_clone_v2',
    name: 'Tajū Kage Bunshin no Jutsu (Multi-Clones)',
    category: 'ninjutsu',
    description: 'Técnica proibida que multiplica o shinobi em milhares. Clones das Sombras produzem 3.5x CPS.',
    cost: D(450000),
    icon: 'users',
    effectType: 'generator_multiplier',
    multiplier: 3.5,
    targetGenerator: 'shadow_clone',
    tier: 2,
    seriesId: 'kage_bunshin',
    requiredUpgradeId: 'shadow_clone_scroll',
  },
  {
    id: 'six_paths_clones_v3',
    name: 'Clones Planetários dos Seis Caminhos',
    category: 'ninjutsu',
    description: 'Clones imbuidos com chakra cósmico de Hagoromo. Clones das Sombras e Tropas Rikudou produzem 8x CPS.',
    cost: D(800000000),
    icon: 'sun',
    effectType: 'generator_multiplier',
    multiplier: 8.0,
    targetGenerator: 'shadow_clone',
    tier: 3,
    seriesId: 'kage_bunshin',
    requiredUpgradeId: 'tajuu_shadow_clone_v2',
  },

  // --- Linhagem Chidori / Raikiri ---
  {
    id: 'chidori_stream',
    name: 'Fluxo Elétrico Chidori Nagashi',
    category: 'ninjutsu',
    description: 'Descarga de alta frequência no solo. Membros da Akatsuki e Taka produzem 2.5x CPS.',
    cost: D(45000000),
    icon: 'zap',
    effectType: 'generator_multiplier',
    multiplier: 2.5,
    targetGenerator: 'akatsuki_member',
    tier: 1,
    seriesId: 'chidori',
  },
  {
    id: 'kirin_thunder',
    name: 'Kirin: Relâmpago Celestial da Tempestade',
    category: 'ninjutsu',
    description: 'Canalização da eletricidade das nuvens em milésimos de segundo. Jōnins de Elite e Capitães ANBU produzem 5x CPS.',
    cost: D(120000000),
    icon: 'zap',
    effectType: 'generator_multiplier',
    multiplier: 5.0,
    targetGenerator: 'jonin',
    tier: 2,
    seriesId: 'chidori',
    requiredUpgradeId: 'chidori_stream',
  },
  {
    id: 'kamui_raikiri_v3',
    name: 'Kamui Raikiri dos Seis Caminhos',
    category: 'ninjutsu',
    description: 'O relâmpago cortador imbuído com intangibilidade do Kamui. Jōnins e Capitães ANBU produzem 10x CPS.',
    cost: D("1200000000000"),
    icon: 'zap',
    effectType: 'generator_multiplier',
    multiplier: 10.0,
    targetGenerator: 'jonin',
    tier: 3,
    seriesId: 'chidori',
    requiredUpgradeId: 'kirin_thunder',
  },

  // --- Linhagem Sharingan ---
  {
    id: 'sharingan',
    name: 'Sharingan Desperto (1 Tomoe)',
    category: 'ninjutsu',
    description: 'Percepção cinética prodigiosa. Jōnins e Capitães da ANBU produzem 2x CPS.',
    cost: D(60000),
    icon: 'eye',
    effectType: 'generator_multiplier',
    multiplier: 2.0,
    targetGenerator: 'jonin',
    tier: 1,
    seriesId: 'sharingan',
  },
  {
    id: 'choku_tomoe',
    name: 'Mangekyō com Padrão Choku Tomoe',
    category: 'ninjutsu',
    description: 'Agilidade ocular e fluidez de movimento sem limites. Hokages da Vila e Elites produzem 2x CPS.',
    cost: D(1200000),
    icon: 'eye',
    effectType: 'generator_multiplier',
    multiplier: 2.0,
    targetGenerator: 'kage',
    tier: 2,
    seriesId: 'sharingan',
    requiredUpgradeId: 'sharingan',
  },
  {
    id: 'mangekyo_kamui_v3',
    name: 'Mangekyō Sharingan Eterno Supremo',
    category: 'ninjutsu',
    description: 'Luz eterna que transcende a cegueira ocular. Multiplica todo o CPS global em 5x.',
    cost: D(5000000000),
    icon: 'eye',
    effectType: 'global_cps',
    multiplier: 5.0,
    tier: 3,
    seriesId: 'sharingan',
    requiredUpgradeId: 'choku_tomoe',
  },

  // --- Linhagem Katon (Fogo) ---
  {
    id: 'fire_ball_jutsu',
    name: 'Estilo Fogo: Jutsu Bola de Fogo Primordial',
    category: 'ninjutsu',
    description: 'Exalação ígnea canônica. Ninjas Gennin produzem 2.5x CPS.',
    cost: D(35000),
    icon: 'flame',
    effectType: 'generator_multiplier',
    multiplier: 2.5,
    targetGenerator: 'genin',
    tier: 1,
    seriesId: 'katon',
  },
  {
    id: 'katon_dragon_fire_v2',
    name: 'Katon: Jutsu Dragão de Chamas (Gōryūka)',
    category: 'ninjutsu',
    description: 'Chamas densas em forma de cabeças dracônicas velozes. Ninjas Gennin e Chūnin produzem 5x CPS.',
    cost: D(1200000),
    icon: 'flame',
    effectType: 'generator_multiplier',
    multiplier: 5.0,
    targetGenerator: 'genin',
    tier: 2,
    seriesId: 'katon',
    requiredUpgradeId: 'fire_ball_jutsu',
  },
  {
    id: 'katon_great_fire_annihilation_v3',
    name: 'Katon: Destruição Majestosa do Fogo (Gōka Mekkyaku)',
    category: 'ninjutsu',
    description: 'Muralha colossal de chamas incandescentes que devora florestas inteiras. Chūnins e Jōnins produzem 10x CPS.',
    cost: D(280000000),
    icon: 'flame',
    effectType: 'generator_multiplier',
    multiplier: 10.0,
    targetGenerator: 'chunin',
    tier: 3,
    seriesId: 'katon',
    requiredUpgradeId: 'katon_dragon_fire_v2',
  },

  // --- Linhagem Suiton (Água) ---
  {
    id: 'water_dragon',
    name: 'Estilo Água: Jutsu Dragão de Água',
    category: 'ninjutsu',
    description: 'Turbilhão hídrico de 44 selos. Sete Espadachins da Névoa produzem 3x CPS.',
    cost: D(850000),
    icon: 'wind',
    effectType: 'generator_multiplier',
    multiplier: 3.0,
    targetGenerator: 'seven_swordsmen',
    tier: 1,
    seriesId: 'suiton',
  },
  {
    id: 'water_shark_bomb_v2',
    name: 'Suiton: Míssil do Tubarão de Água (Suikōdan)',
    category: 'ninjutsu',
    description: 'Bala de tubarão predatória faminta por chakra. Sete Espadachins da Névoa produzem 6x CPS.',
    cost: D(120000000),
    icon: 'wind',
    effectType: 'generator_multiplier',
    multiplier: 6.0,
    targetGenerator: 'seven_swordsmen',
    tier: 2,
    seriesId: 'suiton',
    requiredUpgradeId: 'water_dragon',
  },
  {
    id: 'water_great_shark_bullet_v3',
    name: 'Suiton: Grande Bala do Tubarão Gigante (Daikōdan)',
    category: 'ninjutsu',
    description: 'O colossal tubarão de Kisame que drena jutsus adversários. Sete Espadachins e Akatsuki produzem 12x CPS.',
    cost: D(6500000000),
    icon: 'wind',
    effectType: 'generator_multiplier',
    multiplier: 12.0,
    targetGenerator: 'seven_swordsmen',
    tier: 3,
    seriesId: 'suiton',
    requiredUpgradeId: 'water_shark_bomb_v2',
  },

  // --- Técnicas de Ninjutsu e Invocação Autônomas ---
  {
    id: 'tree_climbing',
    name: 'Exercício de Escalada em Árvores',
    category: 'ninjutsu',
    description: 'Controle contínuo na sola dos pés. Estudantes da Academia produzem 2x CPS.',
    cost: D(1800),
    icon: 'users',
    effectType: 'generator_multiplier',
    multiplier: 2.0,
    targetGenerator: 'academy_student',
    tier: 1,
  },
  {
    id: 'ninja_food_pill',
    name: 'Pílula de Alimento Shinobi (Hyourougan)',
    category: 'ninjutsu',
    description: 'Reabastecimento metabólico acelerado. Clones das Sombras produzem 2x CPS.',
    cost: D(12000),
    icon: 'pill',
    effectType: 'generator_multiplier',
    multiplier: 2.0,
    targetGenerator: 'shadow_clone',
    tier: 1,
  },
  {
    id: 'gravity_training',
    name: 'Treino de Condicionamento Gravitacional',
    category: 'ninjutsu',
    description: 'Superação de pesos corporais. Gennins e Chūnins produzem 2x CPS.',
    cost: D(150000),
    icon: 'trending_up',
    effectType: 'generator_multiplier',
    multiplier: 2.0,
    targetGenerator: 'chunin',
    tier: 1,
  },
  {
    id: 'summoning_scroll',
    name: 'Pacto de Invocação de Sapos',
    category: 'ninjutsu',
    description: 'Contrato de sangue com o Monte Myōboku. Sannins Lendários produzem 2x CPS.',
    cost: D(400000),
    icon: 'scroll',
    effectType: 'generator_multiplier',
    multiplier: 2.0,
    targetGenerator: 'sannin',
    tier: 1,
  },
  {
    id: 'edo_tensei',
    name: 'Invocação Proibida: Reanimação Edo Tensei',
    category: 'ninjutsu',
    description: 'Almas presas em invólucros imortais. Jinchūrikis Perfeitos produzem 2x CPS.',
    cost: D(2500000000),
    icon: 'skull',
    effectType: 'generator_multiplier',
    multiplier: 2.0,
    targetGenerator: 'jinchuriki',
    tier: 2,
  },
  {
    id: 'c4_karura',
    name: 'C4 Karura: Névoa de Micro-bombas Celulares',
    category: 'ninjutsu',
    description: 'Infiltração atômica invisível na circulação. Membros da Akatsuki e Esquadrão Taka produzem 4x CPS.',
    cost: D(85000000000),
    icon: 'cloud',
    effectType: 'generator_multiplier',
    multiplier: 4.0,
    targetGenerator: 'akatsuki_member',
    tier: 2,
  },
  {
    id: 'kamui_dimension',
    name: 'Intangibilidade Espaço-Temporal do Kamui',
    category: 'ninjutsu',
    description: 'Vácuo dimensional que transporta partes do corpo para outra realidade. Multiplica todo o CPS global em 3.5x.',
    cost: D("60000000000000"),
    icon: 'eye',
    effectType: 'global_cps',
    multiplier: 3.5,
    tier: 2,
  },
  {
    id: 'six_paths_sage',
    name: 'Bênção do Sábio dos Seis Caminhos',
    category: 'ninjutsu',
    description: 'Unificação da linhagem de Hagoromo. Multiplica todo o CPS global por 5x.',
    cost: D(80000000000),
    icon: 'sun',
    effectType: 'global_cps',
    multiplier: 5.0,
    tier: 2,
  },
  {
    id: 'infinite_tsukuyomi',
    name: 'Luz Carmesim do Tsukuyomi Infinito',
    category: 'ninjutsu',
    description: 'Genjutsu universal projetado na lua. Multiplica todo o CPS global por 2x.',
    cost: D(250000000000),
    icon: 'moon',
    effectType: 'global_cps',
    multiplier: 2.0,
    tier: 3,
  },
  {
    id: 'divine_tree',
    name: 'Fruto Sagrado da Árvore Divina (Shinju)',
    category: 'ninjutsu',
    description: 'A semente primordial de todo o chakra do cosmos. Multiplica todo o CPS global por 8x.',
    cost: D("2500000000000"),
    icon: 'trees',
    effectType: 'global_cps',
    multiplier: 8.0,
    tier: 3,
  },
  {
    id: 'creation_all_things',
    name: 'Criação de Todas as Coisas (Banbutsu Sōzō)',
    category: 'ninjutsu',
    description: 'Manifesta formas a partir do nada. Multiplica CPS por 10x e Clique por 5x.',
    cost: D("10000000000000"),
    icon: 'infinity',
    effectType: 'global_cps',
    multiplier: 10.0,
    tier: 3,
  },

  // =========================================================================
  // 3. SENJUTSU & TRANSFORMAÇÕES (PICOS TEMPORÁRIOS & SINERGIAS) - V1, V2, V3
  // =========================================================================

  // --- Linhagem Modo Sábio ---
  {
    id: 'sage_mode',
    name: 'Modo Sábio dos Sapos (Senjutsu Perfeito)',
    category: 'senjutsu',
    description: 'Harmonia com a energia natural da terra. +50% em toda a produção passiva global.',
    cost: D(10000000),
    icon: 'sparkles',
    effectType: 'global_cps',
    multiplier: 1.5,
    tier: 1,
    seriesId: 'sage_mode',
  },
  {
    id: 'sage_mode_hashirama_v2',
    name: 'Modo Sábio de Hashirama (Mokuton Primordial)',
    category: 'senjutsu',
    description: 'Senjutsu natural das florestas sagradas de Hashirama. Multiplica todo o CPS global por 3x.',
    cost: D(1200000000),
    icon: 'trees',
    effectType: 'global_cps',
    multiplier: 3.0,
    tier: 2,
    seriesId: 'sage_mode',
    requiredUpgradeId: 'sage_mode',
  },
  {
    id: 'six_paths_senjutsu',
    name: 'Senjutsu dos Seis Caminhos Divino',
    category: 'senjutsu',
    description: 'Plena soberania sobre a realidade física e esferas negras. Multiplica todo o CPS global por 5x.',
    cost: D("50000000000000"),
    icon: 'sun',
    effectType: 'global_cps',
    multiplier: 5.0,
    tier: 3,
    seriesId: 'sage_mode',
    requiredUpgradeId: 'sage_mode_hashirama_v2',
  },

  // --- Linhagem Kurama (Bijuu) ---
  {
    id: 'kyuubi_cloak',
    name: 'Manto da Kyuubi (Chakra de 1 Cauda)',
    category: 'senjutsu',
    description: 'Chakra corrosivo e ardente. Converte +0.2% do CPS^0.65 ao clique e potencializa liberação dos Portões.',
    cost: D(250000000),
    icon: 'flame',
    effectType: 'click_cps_ratio',
    multiplier: 0.002,
    tier: 1,
    seriesId: 'kurama',
  },
  {
    id: 'kurama_mode',
    name: 'Modo Kurama Completo (Sincronia Total)',
    category: 'senjutsu',
    description: 'União fraternal com a Besta de Nove Caudas. Multiplica todo o CPS global por 2.5x.',
    cost: D(800000000),
    icon: 'flame',
    effectType: 'global_cps',
    multiplier: 2.5,
    tier: 2,
    seriesId: 'kurama',
    requiredUpgradeId: 'kyuubi_cloak',
  },
  {
    id: 'baryon_fission_strike',
    name: 'Impacto de Fissão Baryon Estelar (Modo Bárion)',
    category: 'senjutsu',
    description: 'A queima definitiva da matéria vital. Converte +2.5% do CPS ao clique e multiplica CPS global por 5x.',
    cost: D("800000000000000000000"),
    icon: 'sun',
    effectType: 'click_cps_ratio',
    multiplier: 0.025,
    tier: 3,
    seriesId: 'kurama',
    requiredUpgradeId: 'kurama_mode',
  },

  // --- Linhagem Susano'o ---
  {
    id: 'susanoo_ribcage_v1',
    name: 'Susano\'o: Caixa Torácica Esquelética',
    category: 'senjutsu',
    description: 'Primeira manifestação defensiva das costelas espectrais de puro chakra. Multiplica o CPS global por 2x.',
    cost: D(350000000),
    icon: 'shield',
    effectType: 'global_cps',
    multiplier: 2.0,
    tier: 1,
    seriesId: 'susanoo',
  },
  {
    id: 'susanoo_armored_v2',
    name: 'Susano\'o: Forma Tengu Blindada',
    category: 'senjutsu',
    description: 'Armadura guerreira e asas de destruição maciça. Multiplica todo o CPS global por 3.5x.',
    cost: D(15000000000),
    icon: 'shield',
    effectType: 'global_cps',
    multiplier: 3.5,
    tier: 2,
    seriesId: 'susanoo',
    requiredUpgradeId: 'susanoo_ribcage_v1',
  },
  {
    id: 'perfect_susanoo',
    name: 'Susano\'o Perfeito Majestoso Alado',
    category: 'senjutsu',
    description: 'Colosso divino destruidor de montanhas. Converte +1.2% do CPS ao clique e multiplica CPS global por 6x.',
    cost: D(8000000000),
    icon: 'shield',
    effectType: 'click_cps_ratio',
    multiplier: 0.012,
    tier: 3,
    seriesId: 'susanoo',
    requiredUpgradeId: 'susanoo_armored_v2',
  },

  // --- Linhagem Amaterasu / Kagutsuchi ---
  {
    id: 'amaterasu_flames_v1',
    name: 'Amaterasu: Chamas Negras Concentradas',
    category: 'senjutsu',
    description: 'Chamas negras que nunca apagam até desintegrar o alvo. Multiplica o CPS global por 2x.',
    cost: D(800000000),
    icon: 'flame',
    effectType: 'global_cps',
    multiplier: 2.0,
    tier: 1,
    seriesId: 'amaterasu',
  },
  {
    id: 'amaterasu_enteraphy',
    name: 'Chamas Eternas de Kagutsuchi (Enton)',
    category: 'senjutsu',
    description: 'Manipulação e moldagem do fogo negro do Mangekyō. Converte +1.5% do CPS ao clique e multiplica CPS por 3x.',
    cost: D("1800000000000"),
    icon: 'flame',
    effectType: 'global_cps',
    multiplier: 3.0,
    tier: 2,
    seriesId: 'amaterasu',
    requiredUpgradeId: 'amaterasu_flames_v1',
  },
  {
    id: 'amaterasu_inferno_domain_v3',
    name: 'Domínio do Fogo Negro Eterno (Enton Kaen)',
    category: 'senjutsu',
    description: 'Inferno inextinguível de chamas de Enton cobrindo a terra. Multiplica todo o CPS por 6x e concede +3.0% de CPS ao clique.',
    cost: D("22000000000000"),
    icon: 'flame',
    effectType: 'global_cps',
    multiplier: 6.0,
    tier: 3,
    seriesId: 'amaterasu',
    requiredUpgradeId: 'amaterasu_enteraphy',
  },

  // --- Linhagem Gravidade Seis Caminhos ---
  {
    id: 'shinra_tensei_v1',
    name: 'Shinra Tensei: Repulsão Celeste Celestial',
    category: 'senjutsu',
    description: 'Força gravitacional repulsiva do Caminho Deva do Rinnegan. Jinchūrikis e Tropas Divinas produzem 2.5x CPS.',
    cost: D(500000000),
    icon: 'orbit',
    effectType: 'generator_multiplier',
    multiplier: 2.5,
    targetGenerator: 'jinchuriki',
    tier: 1,
    seriesId: 'six_paths_gravity',
  },
  {
    id: 'chibaku_tensei_planetary',
    name: 'Chibaku Tensei Planetário dos Seis Caminhos',
    category: 'senjutsu',
    description: 'Colapso gravitacional que aprisiona continentes inteiros no céu. Manifestações Bijuu e Rinnegan produzem 8x CPS.',
    cost: D("4000000000000000000"),
    icon: 'orbit',
    effectType: 'generator_multiplier',
    multiplier: 8.0,
    targetGenerator: 'bijuu_manifestation',
    tier: 2,
    seriesId: 'six_paths_gravity',
    requiredUpgradeId: 'shinra_tensei_v1',
  },
  {
    id: 'tengai_shinsei_meteor_v3',
    name: 'Tengai Shinsei: Queda Dupla de Meteoros',
    category: 'senjutsu',
    description: 'Atração gravitacional estelar que puxa dois meteoros gigantes da estratosfera. Tropas do Rinnegan produzem 16x CPS.',
    cost: D("180000000000000000000"),
    icon: 'moon',
    effectType: 'generator_multiplier',
    multiplier: 16.0,
    targetGenerator: 'rinnegan_six_paths',
    tier: 3,
    seriesId: 'six_paths_gravity',
    requiredUpgradeId: 'chibaku_tensei_planetary',
  },

  // --- Técnicas Divinas Autônomas ---
  {
    id: 'otsutsuki_power',
    name: 'Herança Genética Otsutsuki Primordial',
    category: 'senjutsu',
    description: 'Poder divino transcendental. Multiplica CPS por 6x e Clique Manual por 4x.',
    cost: D("800000000000"),
    icon: 'crown',
    effectType: 'global_cps',
    multiplier: 6.0,
    tier: 3,
  },
  {
    id: 'sage_art_wood',
    name: 'Arte Sábia: Vários Milhares de Mãos Verdadeiras',
    category: 'senjutsu',
    description: 'A colossal estátua búdica de madeira de Hashirama. Multiplica CPS global por 4x.',
    cost: D("15000000000000"),
    icon: 'trees',
    effectType: 'global_cps',
    multiplier: 4.0,
    tier: 3,
  },
  {
    id: 'senpo_shinsu_senju',
    name: 'Arte Sábia Suprema dos Senju Ancestrais',
    category: 'senjutsu',
    description: 'A monumental estátua de madeira de Hashirama em sintonia divina. Elites Senju e Guardiões de Hamura produzem 10x CPS.',
    cost: D("900000000000000000"),
    icon: 'trees',
    effectType: 'generator_multiplier',
    multiplier: 10.0,
    targetGenerator: 'senju_elite',
    tier: 3,
  },
  {
    id: 'creation_rebirth',
    name: 'Renascimento da Criação (Byakugō no In)',
    category: 'senjutsu',
    description: 'Divisão celular contínua sem limite. Multiplica todo o CPS global em 4.5x permanentemente.',
    cost: D("5000000000000000000000"),
    icon: 'sparkles',
    effectType: 'global_cps',
    multiplier: 4.5,
    tier: 3,
  },

  // =========================================================================
  // 4. FŪINJUTSU & ECONOMIA (EFICIÊNCIA & DESCONTOS) - V1, V2, V3 & ESPECIAIS
  // =========================================================================

  // --- Linhagem Selo Uzumaki ---
  {
    id: 'adamantine_chains',
    name: 'Correntes Adamantinas do Clã Uzumaki',
    category: 'fuinjutsu',
    description: 'Chakra condensado capaz de prender Bijuus. Reduz custo de geradores em 8%.',
    cost: D(80000000),
    icon: 'layers',
    effectType: 'generator_cost_discount',
    multiplier: 0.08,
    tier: 1,
    seriesId: 'uzumaki_seal',
  },
  {
    id: 'uzumaki_adamantine_domain',
    name: 'Domínio das Correntes Espirituais Uzumaki',
    category: 'fuinjutsu',
    description: 'Barreira impenetrável de puro chakra. Reduz o custo de todas as tropas em 10% e concede +30% de CPS global.',
    cost: D(7500000000),
    icon: 'shield',
    effectType: 'generator_cost_discount',
    multiplier: 0.10,
    tier: 2,
    seriesId: 'uzumaki_seal',
    requiredUpgradeId: 'adamantine_chains',
  },
  {
    id: 'uzumaki_creation_temple_v3',
    name: 'Santuário Primordial de Selamento Uzumaki',
    category: 'fuinjutsu',
    description: 'O templo de máscaras sagradas de Uzushio. Reduz custo de todas as tropas em 15% adicional e multiplica CPS por 1.75x.',
    cost: D("1500000000000"),
    icon: 'layers',
    effectType: 'generator_cost_discount',
    multiplier: 0.15,
    tier: 3,
    seriesId: 'uzumaki_seal',
    requiredUpgradeId: 'uzumaki_adamantine_domain',
  },

  // --- Linhagem Selamento dos Oito Trigramas ---
  {
    id: 'four_symbols_seal',
    name: 'Selo de Quatro Símbolos (Shishō Fūin)',
    category: 'fuinjutsu',
    description: 'Estrutura geométrica de confinamento. Reduz o custo de compra de todos os geradores em 4%.',
    cost: D(85000),
    icon: 'shield',
    effectType: 'generator_cost_discount',
    multiplier: 0.04,
    tier: 1,
    seriesId: 'trigram_seal',
  },
  {
    id: 'eight_trigrams_seal',
    name: 'Estilo de Selamento de Oito Trigramas',
    category: 'fuinjutsu',
    description: 'Dois selos entrelaçados para circulação contínua. Reduz custo de geradores em mais 6%.',
    cost: D(2500000),
    icon: 'shield_alert',
    effectType: 'generator_cost_discount',
    multiplier: 0.06,
    tier: 2,
    seriesId: 'trigram_seal',
    requiredUpgradeId: 'four_symbols_seal',
  },
  {
    id: 'reaper_seal',
    name: 'Selo Ceifador da Morte (Shiki Fūjin)',
    category: 'fuinjutsu',
    description: 'Pacto proibido com o Shinigami. Reduz custo de compra em 8% e converte +0.8% do CPS^0.65 ao clique.',
    cost: D(35000000),
    icon: 'skull',
    effectType: 'click_cps_ratio',
    multiplier: 0.008,
    tier: 3,
    seriesId: 'trigram_seal',
    requiredUpgradeId: 'eight_trigrams_seal',
  },

  // --- Linhagem Karma Ōtsutsuki ---
  {
    id: 'karma_seal',
    name: 'Marca de Selamento do Karma Celestial',
    category: 'fuinjutsu',
    description: 'Backup genético supremo. Reduz custo de todos os geradores em 10% e duplica acúmulo offline.',
    cost: D(12000000000),
    icon: 'hexagon',
    effectType: 'generator_cost_discount',
    multiplier: 0.10,
    tier: 1,
    seriesId: 'karma_otsutsuki',
  },
  {
    id: 'amenotejikara_shift',
    name: 'Inversão Espaço-Temporal de Amenotejikara',
    category: 'fuinjutsu',
    description: 'Troca instantânea de posições com qualquer ponto do espaço. Reduz custo de todas as tropas em 15% adicional.',
    cost: D("15000000000000000"),
    icon: 'disc',
    effectType: 'generator_cost_discount',
    multiplier: 0.15,
    tier: 2,
    seriesId: 'karma_otsutsuki',
    requiredUpgradeId: 'karma_seal',
  },
  {
    id: 'shibai_divine_domain_v3',
    name: 'Shinjutsu Supremo de Shibai Ōtsutsuki',
    category: 'fuinjutsu',
    description: 'A transcendência corpórea além da realidade tridimensional. Reduz custos em 20% e dobra (2x) todo o CPS global.',
    cost: D("88000000000000000000"),
    icon: 'infinity',
    effectType: 'generator_cost_discount',
    multiplier: 0.20,
    tier: 3,
    seriesId: 'karma_otsutsuki',
    requiredUpgradeId: 'amenotejikara_shift',
  },

  // --- Fūinjutsu & Eficiência Autônomos ---
  {
    id: 'sealing_scroll',
    name: 'Selo de Armazenamento Básico',
    category: 'fuinjutsu',
    description: 'Compressão eficiente de pergaminhos. +10% de eficiência global em toda a economia.',
    cost: D(500),
    icon: 'scroll',
    effectType: 'global_cps',
    multiplier: 1.1,
    tier: 1,
  },
  {
    id: 'tactical_kunai',
    name: 'Kunai Tática com Selo Teleportador',
    category: 'fuinjutsu',
    description: 'Arma balanceada para desdobramentos táticos. +15% de eficiência econômica global.',
    cost: D(1000),
    icon: 'sword',
    effectType: 'global_cps',
    multiplier: 1.15,
    tier: 1,
  },
  {
    id: 'ninja_sandals',
    name: 'Sandálias de Deslocamento Rápido',
    category: 'fuinjutsu',
    description: 'Aderência e rapidez em terrenos hostis. +20% de velocidade na taxa de chakra.',
    cost: D(3000),
    icon: 'footprints',
    effectType: 'global_cps',
    multiplier: 1.2,
    tier: 1,
  },
  {
    id: 'chakra_concentration',
    name: 'Concentração de Fluxo e Redução de Atrito',
    category: 'fuinjutsu',
    description: 'Minimiza o desperdício de energia. Reduz o custo de compra de todos os geradores em 5%.',
    cost: D(4500),
    icon: 'percent',
    effectType: 'generator_cost_discount',
    multiplier: 0.05,
    tier: 1,
  },
];

export const UPGRADES_BY_ID = Object.fromEntries(
  TECHNIQUE_UPGRADES.map((u) => [u.id, u])
) as Record<string, TechniqueUpgrade>;
