import { D } from './BigNumber';
import { GeneratorItem, UpgradeItem } from '../types/economy';
import { ClanNode } from '../types/prestige';

export const INITIAL_GENERATORS: Record<string, GeneratorItem> = {
  // --- TIER: INICIANTE (Academia até Elite de Konoha) ---
  academy_student: {
    id: 'academy_student',
    name: 'Estudante da Academia',
    avatar: 'academy_student',
    baseCost: D(98),
    baseCPS: D(0.5),
    level: 0,
    unlocked: true,
    tierCategory: 'INICIANTE',
    lore: 'Jovens aspirantes moldando os primeiros circuitos de chakra e dominando o Bunshin no Jutsu.',
  },
  shadow_clone: {
    id: 'shadow_clone',
    name: 'Clone das Sombras',
    avatar: 'shadow_clone',
    baseCost: D(650),
    baseCPS: D(2.0),
    level: 0,
    unlocked: true,
    tierCategory: 'INICIANTE',
    lore: 'Réplicas sólidas de chakra que realizam tarefas táticas e acumulam experiência simultânea.',
  },
  genin: {
    id: 'genin',
    name: 'Ninja Gennin',
    avatar: 'genin',
    baseCost: D(3900),
    baseCPS: D(8.0),
    level: 0,
    unlocked: false,
    tierCategory: 'INICIANTE',
    lore: 'Graduados em equipes de três sob a tutela de um Jōnin, cumprindo missões básicas de Rank D e C.',
  },
  chunin: {
    id: 'chunin',
    name: 'Ninja Chūnin',
    avatar: 'chunin',
    baseCost: D(22750),
    baseCPS: D(35.0),
    level: 0,
    unlocked: false,
    tierCategory: 'INICIANTE',
    lore: 'Líderes de esquadrão tático com capacidade analítica comprovada no lendário Exame Chūnin.',
  },
  jonin: {
    id: 'jonin',
    name: 'Ninja Jōnin de Elite',
    avatar: 'jonin',
    baseCost: D(130000),
    baseCPS: D(150.0),
    level: 0,
    unlocked: false,
    tierCategory: 'ELITE',
    lore: 'Mestres militares que dominam ao menos duas transformações da natureza com maestria letal.',
  },
  anbu: {
    id: 'anbu',
    name: 'Capitão da ANBU',
    avatar: 'anbu',
    baseCost: D(780000),
    baseCPS: D(600.0),
    level: 0,
    unlocked: false,
    tierCategory: 'ELITE',
    lore: 'Força tática de operações negras e assassinatos silenciosos mascarados sob ordens diretas do Hokage.',
  },
  sannin: {
    id: 'sannin',
    name: 'Sannin Lendário',
    avatar: 'sannin',
    baseCost: D(4550000),
    baseCPS: D(2500.0),
    level: 0,
    unlocked: false,
    tierCategory: 'ELITE',
    lore: 'Veteranos da Segunda Guerra Ninja com invocações gigantescas e reservas colossais de chakra.',
  },
  kage: {
    id: 'kage',
    name: 'Hokage da Vila',
    avatar: 'kage',
    baseCost: D(29250000),
    baseCPS: D(12000.0),
    level: 0,
    unlocked: false,
    tierCategory: 'ELITE',
    lore: 'O líder supremo e guardião absoluto da Vila Oculta da Folha, reverenciado por nações inteiras.',
  },
  jinchuriki: {
    id: 'jinchuriki',
    name: 'Jinchūriki Perfeito',
    avatar: 'jinchuriki',
    baseCost: D(195000000),
    baseCPS: D(65000.0),
    level: 0,
    unlocked: false,
    tierCategory: 'ELITE',
    lore: 'Hospedeiros em sincronia simbiótica total com Bestas com Cauda, acessando oceanos de poder destrutivo.',
  },
  rikudou: {
    id: 'rikudou',
    name: 'Sábio dos Seis Caminhos',
    avatar: 'rikudou',
    baseCost: D(1300000000),
    baseCPS: D(350000.0),
    level: 0,
    unlocked: false,
    tierCategory: 'ELITE',
    lore: 'A linhagem de Hagoromo portadora do Rinnegan e das Gudōdama moldando a realidade terrena.',
  },

  // --- TIER: LENDÁRIO (Invocações, Forças Especiais e Clãs) ---
  toad_summon: {
    id: 'toad_summon',
    name: 'Gamabunta (Sapo Chefe)',
    avatar: 'toad_summon',
    baseCost: D(9750000000),
    baseCPS: D(1800000.0),
    level: 0,
    unlocked: false,
    tierCategory: 'LENDARIO',
    lore: 'Lorde do Monte Myōboku com lâmina dosashu empunhada e jatos de óleo vulcânico de Katon.',
  },
  slug_summon: {
    id: 'slug_summon',
    name: 'Katsuyu da Floresta Shikkotsu',
    avatar: 'slug_summon',
    baseCost: D(65000000000),
    baseCPS: D(8500000.0),
    level: 0,
    unlocked: false,
    tierCategory: 'LENDARIO',
    lore: 'Entidade imortal que regenera divisões inteiras de guerreiros simultaneamente com telepatia ácida.',
  },
  snake_summon: {
    id: 'snake_summon',
    name: 'Manda da Caverna Ryūchi',
    avatar: 'snake_summon',
    baseCost: D(487500000000),
    baseCPS: D(40000000.0),
    level: 0,
    unlocked: false,
    tierCategory: 'LENDARIO',
    lore: 'Serpente titânica voraz que rasteja sob a terra estilhaçando rochedos com escamas impenetráveis.',
  },
  sound_five: {
    id: 'sound_five',
    name: 'Quarteto do Som (Selo Nível 2)',
    avatar: 'sound_five',
    baseCost: D(3250000000000),
    baseCPS: D(180000000.0),
    level: 0,
    unlocked: false,
    tierCategory: 'LENDARIO',
    lore: 'Guardiões de Orochimaru fortalecidos pelo Selo Amaldiçoado de segundo estágio e barreiras sonoras.',
  },
  seven_swordsmen: {
    id: 'seven_swordsmen',
    name: 'Sete Espadachins da Névoa',
    avatar: 'seven_swordsmen',
    baseCost: D(22750000000000),
    baseCPS: D(800000000.0),
    level: 0,
    unlocked: false,
    tierCategory: 'LENDARIO',
    lore: 'Os mestres lendários de Kirigakure empunhando Samehada, Kubikiribōchō e lâminas lendárias.',
  },
  akatsuki_member: {
    id: 'akatsuki_member',
    name: 'Membro da Akatsuki',
    avatar: 'akatsuki_member',
    baseCost: D(162500000000000),
    baseCPS: D(3500000000.0),
    level: 0,
    unlocked: false,
    tierCategory: 'LENDARIO',
    lore: 'Renegados de manto negro com nuvens vermelhas, caçadores implacáveis das nove Bestas com Cauda.',
  },
  taka_member: {
    id: 'taka_member',
    name: 'Esquadrão Taka',
    avatar: 'taka_member',
    baseCost: D(1170000000000000),
    baseCPS: D(15000000000.0),
    level: 0,
    unlocked: false,
    tierCategory: 'LENDARIO',
    lore: 'Grupo dissidente liderado por Sasuke Uchiha com suporte sensorial, regenerativo e de força bruta.',
  },
  edo_tensei_warrior: {
    id: 'edo_tensei_warrior',
    name: 'Guerreiro Reanimado',
    avatar: 'edo_tensei_warrior',
    baseCost: D(7800000000000000),
    baseCPS: D(65000000000.0),
    level: 0,
    unlocked: false,
    tierCategory: 'LENDARIO',
    lore: 'Lendas de guerras passadas com chakra infinito e corpos reconstituídos de poeira e cinzas.',
  },
  hyuga_elite: {
    id: 'hyuga_elite',
    name: 'Elite do Clã Hyūga',
    avatar: 'hyuga_elite',
    baseCost: D(55250000000000000),
    baseCPS: D(280000000000.0),
    level: 0,
    unlocked: false,
    tierCategory: 'LENDARIO',
    lore: 'Mestres do Punho Suave e dos Oito Trigramas Sessenta e Quatro Palmas bloqueando o fluxo de chakra.',
  },
  uchiha_elite: {
    id: 'uchiha_elite',
    name: 'Elite do Clã Uchiha',
    avatar: 'uchiha_elite',
    baseCost: D(390000000000000000),
    baseCPS: D(1200000000000.0),
    level: 0,
    unlocked: false,
    tierCategory: 'LENDARIO',
    lore: 'Guerreiros do Mangekyō empunhando costelas de Susano\'o e genjutsus visuais instantâneos.',
  },
  senju_elite: {
    id: 'senju_elite',
    name: 'Elite do Clã Senju',
    avatar: 'senju_elite',
    baseCost: D("2925000000000000000"),
    baseCPS: D(5000000000000.0),
    level: 0,
    unlocked: false,
    tierCategory: 'LENDARIO',
    lore: 'Descendentes de Asura com vitalidade avassaladora e afinidade com todas as transmutações terrestres.',
  },

  // --- TIER: CÓSMICO (Entidades Bijuu, Reencarnações e Clãs Celestiais) ---
  otsutsuki_spirit: {
    id: 'otsutsuki_spirit',
    name: 'Espírito Otsutsuki',
    avatar: 'otsutsuki_spirit',
    baseCost: D("22750000000000000000"),
    baseCPS: D(25000000000000.0),
    level: 0,
    unlocked: false,
    tierCategory: 'COSMICO',
    lore: 'Almas etéreas que vagam através das dobras dimensionais aguardando novos receptáculos de Karma.',
  },
  bijuu_manifestation: {
    id: 'bijuu_manifestation',
    name: 'Manifestação Bijuu',
    avatar: 'bijuu_manifestation',
    baseCost: D("182000000000000000000"),
    baseCPS: D(120000000000000.0),
    level: 0,
    unlocked: false,
    tierCategory: 'COSMICO',
    lore: 'As massas gigantescas de chakra vivo disparando Bombas Bijuu que remodelam a geografia costeira.',
  },
  six_paths_clone: {
    id: 'six_paths_clone',
    name: 'Clone de Rikudou',
    avatar: 'six_paths_clone',
    baseCost: D("1430000000000000000000"),
    baseCPS: D(600000000000000.0),
    level: 0,
    unlocked: false,
    tierCategory: 'COSMICO',
    lore: 'Manifestações de energia pura suspensas sobre Esferas da Busca da Verdade imunes a ninjutsus comuns.',
  },
  shinobi_alliance_division: {
    id: 'shinobi_alliance_division',
    name: 'Divisão da Aliança Shinobi',
    avatar: 'shinobi_alliance_division',
    baseCost: D("11700000000000000000000"),
    baseCPS: D("3000000000000000"),
    level: 0,
    unlocked: false,
    tierCategory: 'COSMICO',
    lore: 'Regimentos colossais marchando sob o mesmo kanji de Shinobi na Quarta Grande Guerra Ninja.',
  },
  kaguya_creation: {
    id: 'kaguya_creation',
    name: 'Criação Primordial de Kaguya',
    avatar: 'kaguya_creation',
    baseCost: D("97500000000000000000000"),
    baseCPS: D("15000000000000000"),
    level: 0,
    unlocked: false,
    tierCategory: 'COSMICO',
    lore: 'Monólitos orgânicos e exércitos de Zetsus Brancos criados a partir dos humanos presos no Tsukuyomi.',
  },
  hamura_guardian: {
    id: 'hamura_guardian',
    name: 'Guardião Celestial de Hamura',
    avatar: 'hamura_guardian',
    baseCost: D("780000000000000000000000"),
    baseCPS: D("80000000000000000"),
    level: 0,
    unlocked: false,
    tierCategory: 'COSMICO',
    lore: 'Guardiões do Tenseigan estacionados no palácio lunar de Hamura canalizando feixes óticos solares.',
  },
  indras_reincarnation: {
    id: 'indras_reincarnation',
    name: 'Reencarnação de Indra',
    avatar: 'indras_reincarnation',
    baseCost: D("6500000000000000000000000"),
    baseCPS: D("400000000000000000"),
    level: 0,
    unlocked: false,
    tierCategory: 'COSMICO',
    lore: 'O gênio orgulhoso que herdou os olhos e chakra potente de Hagoromo moldando o Susano\'o primordial.',
  },
  asuras_reincarnation: {
    id: 'asuras_reincarnation',
    name: 'Reencarnação de Asura',
    avatar: 'asuras_reincarnation',
    baseCost: D("55250000000000000000000000"),
    baseCPS: D("2000000000000000000"),
    level: 0,
    unlocked: false,
    tierCategory: 'COSMICO',
    lore: 'O avatar da determinação corporal com esferas douradas de chakra divino e vínculos inquebráveis.',
  },
  otsutsuki_god: {
    id: 'otsutsuki_god',
    name: 'Deus Otsutsuki',
    avatar: 'otsutsuki_god',
    baseCost: D("487500000000000000000000000"),
    baseCPS: D("10000000000000000000"),
    level: 0,
    unlocked: false,
    tierCategory: 'DIVINO',
    lore: 'Consumidores de incontáveis Frutos Divinos que atingiram a imortalidade cósmica estelar.',
  },

  // --- NOVAS TROPAS (12 ADICIONAIS: EXPANDINDO PARA 42 TROPAS) ---
  rinnegan_six_paths: {
    id: 'rinnegan_six_paths',
    name: 'Seis Caminhos de Pain',
    avatar: 'rinnegan_six_paths',
    baseCost: D("4.2e27"),
    baseCPS: D("8.0e19"),
    level: 0,
    unlocked: false,
    tierCategory: 'LENDARIO',
    lore: 'Seis corpos sincronizados pela visão compartilhada do Rinnegan, manipulando atração, repulsão e almas.',
  },
  wood_golem_senju: {
    id: 'wood_golem_senju',
    name: 'Golem de Madeira de Hashirama',
    avatar: 'wood_golem_senju',
    baseCost: D("3.6e28"),
    baseCPS: D("7.5e20"),
    level: 0,
    unlocked: false,
    tierCategory: 'LENDARIO',
    lore: 'Entidade de Mokuton puro que envolve o Dragão de Madeira, capaz de repelir ataques de nível calamidade.',
  },
  reanimated_hokages: {
    id: 'reanimated_hokages',
    name: 'Os Quatro Primeiros Hokages',
    avatar: 'reanimated_hokages',
    baseCost: D("3.1e29"),
    baseCPS: D("7.0e21"),
    level: 0,
    unlocked: false,
    tierCategory: 'LENDARIO',
    lore: 'Os quatro mestres fundadores de Konoha erguendo barreiras absolutas de chamas escarlates inexpugnáveis.',
  },
  juubi_primordial: {
    id: 'juubi_primordial',
    name: 'Juubi Primordial (Dez Caudas)',
    avatar: 'juubi_primordial',
    baseCost: D("2.8e30"),
    baseCPS: D("6.8e22"),
    level: 0,
    unlocked: false,
    tierCategory: 'COSMICO',
    lore: 'O cataclismo vivo da terra, a monstruosidade de um olho só que personifica o chakra original do planeta.',
  },
  kinshiki_otsutsuki: {
    id: 'kinshiki_otsutsuki',
    name: 'Kinshiki Otsutsuki (Armeiro Celestial)',
    avatar: 'kinshiki_otsutsuki',
    baseCost: D("2.5e31"),
    baseCPS: D("6.5e23"),
    level: 0,
    unlocked: false,
    tierCategory: 'COSMICO',
    lore: 'Guardião devoto com a capacidade de materializar machados, lanças e espadas de luz vermelha que cortam mundos.',
  },
  urashiki_otsutsuki: {
    id: 'urashiki_otsutsuki',
    name: 'Urashiki Otsutsuki (Pescador Espacial)',
    avatar: 'urashiki_otsutsuki',
    baseCost: D("2.3e32"),
    baseCPS: D("6.2e24"),
    level: 0,
    unlocked: false,
    tierCategory: 'COSMICO',
    lore: 'Portador do anzol de dobra espacial capaz de pescar e armazenar as técnicas e o chakra de oponentes em frascos.',
  },
  momoshiki_fused: {
    id: 'momoshiki_fused',
    name: 'Momoshiki Otsutsuki (Forma Fundida)',
    avatar: 'momoshiki_fused',
    baseCost: D("2.1e33"),
    baseCPS: D("6.0e25"),
    level: 0,
    unlocked: false,
    tierCategory: 'COSMICO',
    lore: 'A transmutação após consumir Kinshiki: Rinnegan dourado na testa e poder para criar cães monstruosos de lava.',
  },
  isshiki_otsutsuki: {
    id: 'isshiki_otsutsuki',
    name: 'Isshiki Otsutsuki (Daikokuten)',
    avatar: 'isshiki_otsutsuki',
    baseCost: D("1.9e34"),
    baseCPS: D("5.8e26"),
    level: 0,
    unlocked: false,
    tierCategory: 'DIVINO',
    lore: 'O soberano do tempo e espaço, invocando cubos monumentais de Daikokuten imunes a leitura sensorial.',
  },
  baryon_mode_manifestation: {
    id: 'baryon_mode_manifestation',
    name: 'Manifestação Modo Baryon',
    avatar: 'baryon_mode_manifestation',
    baseCost: D("1.8e35"),
    baseCPS: D("5.5e27"),
    level: 0,
    unlocked: false,
    tierCategory: 'DIVINO',
    lore: 'A fissão termonuclear de Kurama onde partículas de chakra colidem, exaurindo a vida dos alvos com meros golpes.',
  },
  goddess_kaguya_avatar: {
    id: 'goddess_kaguya_avatar',
    name: 'Kaguya Otsutsuki (Deusa Progenitora)',
    avatar: 'goddess_kaguya_avatar',
    baseCost: D("1.7e36"),
    baseCPS: D("5.2e28"),
    level: 0,
    unlocked: false,
    tierCategory: 'DIVINO',
    lore: 'A Deusa Coelho que governa a gravidade, lava e gelo com ossos perfurantes Tomogoroshi no Haikotsu.',
  },
  shinobi_alliance_hq: {
    id: 'shinobi_alliance_hq',
    name: 'Quartel-General Supremo da Aliança',
    avatar: 'shinobi_alliance_hq',
    baseCost: D("1.6e37"),
    baseCPS: D("5.0e29"),
    level: 0,
    unlocked: false,
    tierCategory: 'DIVINO',
    lore: 'A inteligência tática unificada de todas as Vilas Ocultas guiando milhares de guerreiros como um só organismo.',
  },
  shibai_otsutsuki: {
    id: 'shibai_otsutsuki',
    name: 'Shibai Otsutsuki (Deus Ascendido)',
    avatar: 'shibai_otsutsuki',
    baseCost: D("1.5e38"),
    baseCPS: D("4.8e30"),
    level: 0,
    unlocked: false,
    tierCategory: 'DIVINO',
    lore: 'A entidade cósmica suprema que transcendeu o corpo carnal e atingiu a onipotência, originando todos os Shinjutsus.',
  },
};

export const INITIAL_UPGRADES: Record<string, UpgradeItem> = {
  sealing_scroll: { id: 'sealing_scroll', name: 'Selo de Armazenamento', cost: D(500), description: '+10% de eficiência global', icon: 'sealing_scroll', purchased: false },
  tactical_kunai: { id: 'tactical_kunai', name: 'Kunai Tática', cost: D(1000), description: '+15% de eficiência global', icon: 'tactical_kunai', purchased: false },
  tree_climbing: { id: 'tree_climbing', name: 'Escalada em Árvores', cost: D(1800), description: 'Estudantes produzem 2x', icon: 'tree_climbing', purchased: false },
  ninja_sandals: { id: 'ninja_sandals', name: 'Sandálias Ninja', cost: D(3000), description: '+20% de velocidade de chakra', icon: 'ninja_sandals', purchased: false },
  chakra_concentration: { id: 'chakra_concentration', name: 'Concentração de Chakra', cost: D(4500), description: 'Reduz custo de geradores em 5%', icon: 'chakra_concentration', purchased: false },
  shadow_clone_scroll: { id: 'shadow_clone_scroll', name: 'Pergaminho de Clones', cost: D(7500), description: 'Clones produzem +50%', icon: 'shadow_clone_scroll', purchased: false },
  ninja_food_pill: { id: 'ninja_food_pill', name: 'Pílula de Comida Ninja', cost: D(12000), description: 'Clones produzem 2x', icon: 'ninja_food_pill', purchased: false },
  bandana_genin: { id: 'bandana_genin', name: 'Bandana de Gennin', cost: D(25000), description: 'Poder de clique manual +50%', icon: 'bandana_genin', purchased: false },
  sharingan: { id: 'sharingan', name: 'Sharingan (1 Tomoe)', cost: D(60000), description: 'Jōnins e ANBUs produzem 2x', icon: 'sharingan', purchased: false },
  gravity_training: { id: 'gravity_training', name: 'Treino Gravitacional', cost: D(150000), description: 'Gennins e Chūnins produzem 2x', icon: 'gravity_training', purchased: false },
  summoning_scroll: { id: 'summoning_scroll', name: 'Pergaminho de Invocação', cost: D(400000), description: 'Sannins produzem 2x', icon: 'summoning_scroll', purchased: false },
  choku_tomoe: { id: 'choku_tomoe', name: 'Choku Tomoe', cost: D(1200000), description: 'Kages produzem 2x', icon: 'choku_tomoe', purchased: false },
  reaper_seal: { id: 'reaper_seal', name: 'Selo Ceifador da Morte', cost: D(3500000), description: 'Converte +2% do CPS para clique', icon: 'reaper_seal', purchased: false },
  sage_mode: { id: 'sage_mode', name: 'Modo Sábio dos Sapos', cost: D(10000000), description: '+50% em toda a produção', icon: 'sage_mode', purchased: false },
  blade_storm: { id: 'blade_storm', name: 'Tempestade de Lâminas', cost: D(30000000), description: '+30% de poder de clique', icon: 'blade_storm', purchased: false },
  rasengan_mastery: { id: 'rasengan_mastery', name: 'Mestria do Rasengan', cost: D(90000000), description: 'Dobra o poder do clique manual', icon: 'rasengan_mastery', purchased: false },
  kyuubi_cloak: { id: 'kyuubi_cloak', name: 'Manto da Kyuubi', cost: D(250000000), description: 'Converte +0.5% do CPS para clique', icon: 'kyuubi_cloak', purchased: false },
  kurama_mode: { id: 'kurama_mode', name: 'Modo Kurama Completo', cost: D(800000000), description: 'CPS global multiplicado por 2.5x', icon: 'kurama_mode', purchased: false },
  edo_tensei: { id: 'edo_tensei', name: 'Reanimação Edo Tensei', cost: D(2500000000), description: 'Jinchūrikis produzem 2x', icon: 'edo_tensei', purchased: false },
  perfect_susanoo: { id: 'perfect_susanoo', name: 'Susano\'o Perfeito', cost: D(8000000000), description: 'Converte +3% do CPS para clique', icon: 'perfect_susanoo', purchased: false },
  truth_seeking_orbs: { id: 'truth_seeking_orbs', name: 'Esferas da Verdade (Gudōdama)', cost: D(25000000000), description: 'Triplica o clique manual', icon: 'truth_seeking_orbs', purchased: false },
  six_paths_sage: { id: 'six_paths_sage', name: 'Sábio dos Seis Caminhos', cost: D(80000000000), description: 'Multiplica todo o CPS por 5x', icon: 'six_paths_sage', purchased: false },
  infinite_tsukuyomi: { id: 'infinite_tsukuyomi', name: 'Tsukuyomi Infinito', cost: D(250000000000), description: 'Multiplica todo o CPS por 2x', icon: 'infinite_tsukuyomi', purchased: false },
  otsutsuki_power: { id: 'otsutsuki_power', name: 'Herança Genética Otsutsuki', cost: D(800000000000), description: 'Multiplica CPS por 6x e Clique por 4x', icon: 'otsutsuki_power', purchased: false },
  divine_tree: { id: 'divine_tree', name: 'Fruto da Árvore Divina', cost: D(2500000000000), description: 'Multiplica todo o CPS por 8x', icon: 'divine_tree', purchased: false },
  creation_all_things: { id: 'creation_all_things', name: 'Criação de Todas as Coisas', cost: D(10000000000000), description: 'Multiplica CPS por 10x e Clique por 5x', icon: 'creation_all_things', purchased: false },
};

export const GATE_DATA = [
  { id: 1, name: 'Portão da Abertura', cost: 5000 },
  { id: 2, name: 'Portão da Cura', cost: 25000 },
  { id: 3, name: 'Portão da Vida', cost: 100000 },
  { id: 4, name: 'Portão da Dor', cost: 500000 },
  { id: 5, name: 'Portão do Limite', cost: 2500000 },
  { id: 6, name: 'Portão da Visão', cost: 10000000 },
  { id: 7, name: 'Portão da Maravilha', cost: 50000000 },
  { id: 8, name: 'Portão da Morte', cost: 250000000 },
];

export const CLAN_NODES: Record<string, ClanNode> = {
  primordial_chakra: {
    id: 'primordial_chakra',
    name: 'Chakra Primordial',
    branch: 'root',
    icon: 'primordial_chakra',
    cost: 1,
    desc: 'O despertar da centelha original de Hagoromo Otsutsuki. +50% em todo o CPS global.',
    parent: null,
  },
  uzumaki_vitality: {
    id: 'uzumaki_vitality',
    name: 'Linhagem Uzumaki (Vitalidade Infinita)',
    branch: 'senju',
    icon: 'uzumaki_vitality',
    cost: 3,
    desc: 'Força vital e regeneração extraordinárias. Dobra todo o CPS global permanentemente.',
    parent: 'primordial_chakra',
  },
  senju_wood_release: {
    id: 'senju_wood_release',
    name: 'Liberação de Madeira (Mokuton)',
    branch: 'senju',
    icon: 'senju_wood_release',
    cost: 8,
    desc: 'A fusão da terra com a água que molda florestas divinas. Triplica o CPS global.',
    parent: 'uzumaki_vitality',
  },
  sharingan_awakening: {
    id: 'sharingan_awakening',
    name: 'Despertar do Sharingan',
    branch: 'uchiha',
    icon: 'sharingan_awakening',
    cost: 3,
    desc: 'O poder visual do Clã Uchiha. Aumenta a chance de acerto crítico de clique em +10%.',
    parent: 'primordial_chakra',
  },
  mangekyo_sharingan_lineage: {
    id: 'mangekyo_sharingan_lineage',
    name: 'Mangekyō Sharingan Eterno',
    branch: 'uchiha',
    icon: 'mangekyo_sharingan_lineage',
    cost: 8,
    desc: 'O olho que reflete o coração. O clique manual passa a gerar +3% do seu CPS global.',
    parent: 'sharingan_awakening',
  },
  perfect_susanoo_lineage: {
    id: 'perfect_susanoo_lineage',
    name: 'Susano\'o Perfeito Divino',
    branch: 'uchiha',
    icon: 'perfect_susanoo_lineage',
    cost: 20,
    desc: 'Armadura do Deus das Tempestades. Multiplica o poder de clique manual por 10x.',
    parent: 'mangekyo_sharingan_lineage',
  },
  byakugan_vision: {
    id: 'byakugan_vision',
    name: 'Visão dos 360 Graus (Byakugan)',
    branch: 'hyuga',
    icon: 'byakugan_vision',
    cost: 3,
    desc: 'Leitura dos pontos de chakra (Tenketsu). +50% nas recompensas de missões e minigames.',
    parent: 'primordial_chakra',
  },
  chakra_fruit: {
    id: 'chakra_fruit',
    name: 'Fruto Proibido do Clã Divino',
    branch: 'otsutsuki',
    icon: 'chakra_fruit',
    cost: 30,
    desc: 'Consumo do fruto primordial de chakra. Multiplica todo o CPS global em 5x.',
    parent: 'primordial_chakra',
  },
};
