import React from 'react';
import {
  LucideProps,
  User,
  Users,
  Compass,
  Scroll,
  Zap,
  Eye,
  Sparkles,
  Crown,
  Flame,
  Sun,
  Sword,
  Shield,
  Activity,
  Layers,
  Swords,
  Cloud,
  Feather,
  Skull,
  CircleDot,
  Trees,
  Ghost,
  ShieldAlert,
  SunMedium,
  ShieldCheck,
  Orbit,
  Moon,
  Leaf,
  Infinity,
  Target,
  Crosshair,
  Award,
  Clock,
  HeartPulse,
  Boxes,
  Wind,
  FileText,
  Trophy,
  BarChart3,
  HelpCircle,
  CheckCircle2,
  TreePine,
  Footprints,
  Pill,
  Dumbbell,
  Hexagon,
} from 'lucide-react';

interface IconRendererProps extends LucideProps {
  name: string;
}

const ICON_MAP: Record<string, React.ComponentType<LucideProps>> = {
  // Shinobis / Geradores
  academy_student: User,
  shadow_clone: Users,
  genin: Compass,
  chunin: Scroll,
  jonin: Zap,
  anbu: Eye,
  sannin: Sparkles,
  kage: Crown,
  jinchuriki: Flame,
  rikudou: Sun,
  toad_summon: Sword,
  slug_summon: Shield,
  snake_summon: Activity,
  sound_five: Layers,
  seven_swordsmen: Swords,
  akatsuki_member: Cloud,
  taka_member: Feather,
  edo_tensei_warrior: Skull,
  hyuga_elite: CircleDot,
  uchiha_elite: Flame,
  senju_elite: Trees,
  otsutsuki_spirit: Ghost,
  bijuu_manifestation: ShieldAlert,
  six_paths_clone: SunMedium,
  shinobi_alliance_division: ShieldCheck,
  kaguya_creation: Orbit,
  hamura_guardian: Moon,
  indras_reincarnation: Zap,
  asuras_reincarnation: Leaf,
  otsutsuki_god: Infinity,

  // Upgrades
  sealing_scroll: Scroll,
  tactical_kunai: Sword,
  tree_climbing: TreePine,
  ninja_sandals: Footprints,
  chakra_concentration: Target,
  shadow_clone_scroll: Users,
  ninja_food_pill: Pill,
  bandana_genin: Award,
  sharingan: Eye,
  gravity_training: Dumbbell,
  summoning_scroll: Scroll,
  choku_tomoe: CircleDot,
  reaper_seal: Ghost,
  sage_mode: Sparkles,
  blade_storm: Swords,
  rasengan_mastery: Orbit,
  kyuubi_cloak: Flame,
  kurama_mode: Flame,
  edo_tensei: Skull,
  perfect_susanoo: Shield,
  truth_seeking_orbs: Hexagon,
  six_paths_sage: Sun,
  infinite_tsukuyomi: Moon,
  otsutsuki_power: Crown,
  divine_tree: Trees,
  creation_all_things: Infinity,

  // Clãs
  primordial_chakra: Sun,
  uzumaki_vitality: HeartPulse,
  senju_wood_release: Trees,
  sharingan_awakening: Eye,
  mangekyo_sharingan_lineage: CircleDot,
  perfect_susanoo_lineage: Swords,
  byakugan_vision: Eye,
  chakra_fruit: Orbit,

  // Chefes e Desafios (Fallback por Tier / Nome)
  target: Target,
  crosshair: Crosshair,
  swords: Swords,
  skull: Skull,
  flame: Flame,
  zap: Zap,
  wind: Wind,
  scroll: Scroll,
  shield: Shield,
  clock: Clock,
  award: Award,
  trophy: Trophy,
  boxes: Boxes,
  filetext: FileText,
  barchart: BarChart3,
  helpcircle: HelpCircle,
  checkcircle: CheckCircle2,
  checkcircle2: CheckCircle2,
};

export const IconRenderer: React.FC<IconRendererProps> = ({
  name,
  className = 'w-4 h-4',
  size,
  strokeWidth = 1.75,
  ...rest
}) => {
  const normalizedKey = name.toLowerCase().replace(/[^a-z0-9_]/g, '');
  const Component = ICON_MAP[normalizedKey] || ICON_MAP[name] || Target;

  return <Component className={className} size={size} strokeWidth={strokeWidth} {...rest} />;
};
