import React from 'react';
import {
  LucideProps,
  User,
  Users,
  Compass,
  Scroll,
  Zap,
  Eye,
  Sparkles,
  Crown,
  Flame,
  Sun,
  Sword,
  Shield,
  Activity,
  Layers,
  Swords,
  Cloud,
  Feather,
  Skull,
  CircleDot,
  Trees,
  Ghost,
  ShieldAlert,
  SunMedium,
  ShieldCheck,
  Orbit,
  Moon,
  Leaf,
  Infinity,
  Target,
  Crosshair,
  Award,
  Clock,
  HeartPulse,
  Boxes,
  Wind,
  FileText,
  Trophy,
  BarChart3,
  HelpCircle,
  CheckCircle2,
  TreePine,
  Footprints,
  Pill,
  Dumbbell,
  Hexagon,
  Briefcase,
  Disc,
  Hand,
} from 'lucide-react';

interface IconRendererProps extends LucideProps {
  name: string;
}

const ICON_MAP: Record<string, React.ComponentType<LucideProps>> = {
  // Shinobis / Geradores
  academy_student: User,
  shadow_clone: Users,
  genin: Compass,
  chunin: Scroll,
  jonin: Zap,
  anbu: Eye,
  sannin: Sparkles,
  kage: Crown,
  jinchuriki: Flame,
  rikudou: Sun,
  toad_summon: Sword,
  slug_summon: Shield,
  snake_summon: Activity,
  sound_five: Layers,
  seven_swordsmen: Swords,
  akatsuki_member: Cloud,
  taka_member: Feather,
  edo_tensei_warrior: Skull,
  hyuga_elite: CircleDot,
  uchiha_elite: Flame,
  senju_elite: Trees,
  otsutsuki_spirit: Ghost,
  bijuu_manifestation: ShieldAlert,
  six_paths_clone: SunMedium,
  shinobi_alliance_division: ShieldCheck,
  kaguya_creation: Orbit,
  hamura_guardian: Moon,
  indras_reincarnation: Zap,
  asuras_reincarnation: Leaf,
  otsutsuki_god: Infinity,

  // Novas Tropas Lendárias, Cósmicas e Divinas
  rinnegan_six_paths: Eye,
  wood_golem_senju: Trees,
  reanimated_hokages: Crown,
  juubi_primordial: Flame,
  kinshiki_otsutsuki: Sword,
  urashiki_otsutsuki: Compass,
  momoshiki_fused: Sun,
  isshiki_otsutsuki: Hexagon,
  baryon_mode_manifestation: Sparkles,
  goddess_kaguya_avatar: Orbit,
  shinobi_alliance_hq: ShieldCheck,
  shibai_otsutsuki: Infinity,

  // Upgrades
  leaf_great_hurricane_v2: Zap,
  leaf_dragon_whirlwind_v3: Flame,
  rasengan_oodama_v2: Orbit,
  rasen_shuriken_v3: Orbit,
  flying_raijin_guiding_thunder_v2: Zap,
  flying_raijin_jikuukan_v3: Zap,
  tajuu_shadow_clone_v2: Users,
  six_paths_clones_v3: Sun,
  kamui_raikiri_v3: Zap,
  mangekyo_kamui_v3: Eye,
  katon_dragon_fire_v2: Flame,
  katon_great_fire_annihilation_v3: Flame,
  water_shark_bomb_v2: Wind,
  water_great_shark_bullet_v3: Wind,
  sage_mode_hashirama_v2: Trees,
  susanoo_ribcage_v1: Shield,
  susanoo_armored_v2: Shield,
  amaterasu_flames_v1: Flame,
  amaterasu_inferno_domain_v3: Flame,
  shinra_tensei_v1: Orbit,
  tengai_shinsei_meteor_v3: Moon,
  uzumaki_creation_temple_v3: Layers,
  shibai_divine_domain_v3: Infinity,
  flying_raijin_slice: Zap,
  night_guy_dragon: Flame,
  baryon_fission_strike: Sun,
  kirin_thunder: Zap,
  c4_karura: Boxes,
  kamui_dimension: Orbit,
  chibaku_tensei_planetary: Moon,
  amaterasu_enteraphy: Flame,
  senpo_shinsu_senju: Trees,
  creation_rebirth: HeartPulse,
  uzumaki_adamantine_domain: ShieldCheck,
  amenotejikara_shift: Crosshair,
  sealing_scroll: Scroll,
  tactical_kunai: Sword,
  tree_climbing: TreePine,
  ninja_sandals: Footprints,
  chakra_concentration: Target,
  shadow_clone_scroll: Users,
  ninja_food_pill: Pill,
  bandana_genin: Award,
  sharingan: Eye,
  gravity_training: Dumbbell,
  summoning_scroll: Scroll,
  choku_tomoe: CircleDot,
  reaper_seal: Ghost,
  sage_mode: Sparkles,
  blade_storm: Swords,
  rasengan_mastery: Orbit,
  kyuubi_cloak: Flame,
  kurama_mode: Flame,
  edo_tensei: Skull,
  perfect_susanoo: Shield,
  truth_seeking_orbs: Hexagon,
  six_paths_sage: Sun,
  infinite_tsukuyomi: Moon,
  otsutsuki_power: Crown,
  divine_tree: Trees,
  creation_all_things: Infinity,
  leaf_hurricane: Zap,
  lion_combo: Crosshair,
  morning_peacock: Flame,
  daytime_tiger: Target,
  night_guy: Flame,
  fire_ball_jutsu: Flame,
  water_dragon: Wind,
  chidori_stream: Zap,
  sage_art_wood: Trees,
  six_paths_senjutsu: Sun,
  four_symbols_seal: Shield,
  eight_trigrams_seal: ShieldAlert,
  adamantine_chains: Layers,
  karma_seal: Hexagon,
  user: User,

  // Clãs
  primordial_chakra: Sun,
  uzumaki_vitality: HeartPulse,
  senju_wood_release: Trees,
  sharingan_awakening: Eye,
  mangekyo_sharingan_lineage: CircleDot,
  perfect_susanoo_lineage: Swords,
  byakugan_vision: Eye,
  chakra_fruit: Orbit,

  // Chefes e Desafios (Fallback por Tier / Nome)
  target: Target,
  crosshair: Crosshair,
  swords: Swords,
  skull: Skull,
  flame: Flame,
  zap: Zap,
  wind: Wind,
  scroll: Scroll,
  shield: Shield,
  clock: Clock,
  award: Award,
  trophy: Trophy,
  boxes: Boxes,
  filetext: FileText,
  barchart: BarChart3,
  helpcircle: HelpCircle,
  checkcircle: CheckCircle2,
  checkcircle2: CheckCircle2,
  briefcase: Briefcase,
  disc: Disc,
  hand: Hand,
  footprints: Footprints,
};

export const IconRenderer: React.FC<IconRendererProps> = ({
  name,
  className = 'w-4 h-4',
  size,
  strokeWidth = 1.75,
  ...rest
}) => {
  const normalizedKey = name.toLowerCase().replace(/[^a-z0-9_]/g, '');
  const Component = ICON_MAP[normalizedKey] || ICON_MAP[name] || Target;

  return <Component className={className} size={size} strokeWidth={strokeWidth} {...rest} />;
};
